### ISSUE TITLE
Peer connection continuously resetting

### ISSUE THREAD

**Issue by lpellegr** [QuarkChain/pyquarkchain#166]
Using a simple configuration with 3 clusters, each on a different machine (one is the bootstrap and 2 other connect to the bootstrap), I have one cluster master that keeps closing the peer connection but then reconnects, again and again:

> SLAVE_S108: I1016 18:17:59.847517 shard.py:136] [236] received new header with height 66
> SLAVE_S120: I1016 18:17:59.847553 shard.py:136] [504] received new header with height 55
> SLAVE_S29: I1016 18:17:59.848172 shard.py:136] [285] received new header with height 47
> SLAVE_S24: I1016 18:17:59.848497 shard.py:136] [536] received new header with height 47
> SLAVE_S33: I1016 18:17:59.849180 shard.py:136] [289] received new header with height 49
> SLAVE_S126: I1016 18:17:59.849541 shard.py:136] [766] received new header with height 48
> SLAVE_S33: I1016 18:17:59.850793 shard.py:136] [161] received new header with height 54
> SLAVE_S14: I1016 18:17:59.850684 shard.py:136] [398] received new header with height 42
> SLAVE_S54: I1016 18:17:59.863734 shard.py:136] [822] received new header with height 47
> SLAVE_S108: I1016 18:17:59.872091 shard.py:136] [620] received new header with height 51
> SLAVE_S99: I1016 18:17:59.878481 shard.py:136] [995] received new header with height 48
> SLAVE_S127: E1016 18:17:59.878653 slave.py:203] Traceback (most recent call last):
> SLAVE_S127: File "slave.py", line 201, in handle_add_root_block_request
> SLAVE_S127: switched = await shard.add_root_block(req.root_block)
> SLAVE_S127: File "/home/laurent_pellegrino/pyquarkchain/quarkchain/cluster/shard.py", line 462, in add_root_block
> SLAVE_S127: return self.state.add_root_block(root_block)
> SLAVE_S127: File "/home/laurent_pellegrino/pyquarkchain/quarkchain/cluster/shard_state.py", line 1048, in add_root_block
> SLAVE_S127: raise ValueError("cannot find previous root block in pool")
> SLAVE_S127: ValueError: cannot find previous root block in pool
> SLAVE_S127: 
> SLAVE_S99: I1016 18:17:59.879714 shard.py:136] [99] received new header with height 43
> SLAVE_S96: I1016 18:17:59.880505 shard.py:136] [864] received new header with height 49
> MASTER: E1016 18:17:59.881408 master.py:100] Traceback (most recent call last):
> MASTER: File "master.py", line 98, in sync
> MASTER: await self.__run_sync()
> MASTER: File "master.py", line 156, in __run_sync
> MASTER: await self.__add_block(block)
> MASTER: File "master.py", line 194, in __add_block
> MASTER: await self.master_server.add_root_block(root_block)
> MASTER: File "master.py", line 1015, in add_root_block
> MASTER: check(all([resp.error_code == 0 for _, resp, _ in result_list]))
> MASTER: File "/home/laurent_pellegrino/pyquarkchain/quarkchain/utils.py", line 54, in check
> MASTER: raise AssertionError(msg)
> MASTER: AssertionError
> MASTER: 
> SLAVE_S127: I1016 18:17:59.881958 shard.py:136] [1023] received new header with height 54
> MASTER: I1016 18:17:59.882185 simple_network.py:172] Closing peer 13e8fe6de8394401c91735981ee39f6a4577548aa12cf471ec49fd61837993fd with the following reason:
> MASTER: I1016 18:17:59.882568 simple_network.py:148] Peer 13e8fe6de8394401c91735981ee39f6a4577548aa12cf471ec49fd61837993fd disconnected, remaining 1
> SLAVE_S127: I1016 18:17:59.884073 shard.py:136] [127] received new header with height 41
> SLAVE_S127: I1016 18:17:59.885576 shard.py:136] [255] received new header with height 46
> SLAVE_S127: I1016 18:17:59.886909 shard.py:136] [639] received new header with height 39
> MASTER: I1016 18:20:56.125511 master.py:146] [R] syncing from 4 10264a68b8c4e31c7a74a8d266444d42459698e200c1e1454eeaa433e55744a2
> MASTER: I1016 18:21:02.707984 master.py:150] [R] downloaded 1 blocks from peer
> SLAVE_S15: I1016 18:21:03.519918 slave.py:406] [15] sync request from master, downloaded 3 blocks (25 - 27)
> SLAVE_S20: I1016 18:21:03.520654 slave.py:406] [20] sync request from master, downloaded 2 blocks (23 - 24)
> SLAVE_S4: I1016 18:21:03.520847 slave.py:406] [4] sync request from master, downloaded 4 blocks (26 - 29)
> SLAVE_S0: I1016 18:21:03.520806 slave.py:406] [0] sync request from master, downloaded 5 blocks (24 - 28)
> SLAVE_S15: E1016 18:21:03.520998 shard.py:597] Traceback (most recent call last):
> SLAVE_S15: File "/home/laurent_pellegrino/pyquarkchain/quarkchain/cluster/shard.py", line 595, in add_block_list_for_sync
> SLAVE_S15: xshard_list = self.state.add_block(block)
> SLAVE_S15: File "/home/laurent_pellegrino/pyquarkchain/quarkchain/cluster/shard_state.py", line 656, in add_block
> SLAVE_S15: self.__validate_block(block)
> SLAVE_S15: File "/home/laurent_pellegrino/pyquarkchain/quarkchain/cluster/shard_state.py", line 424, in __validate_block
> SLAVE_S15: block.header.hash_prev_minor_block.hex(),
> SLAVE_S15: ValueError: [15] prev block not found, block height 25 prev hash 04d657110e2b71da93acff13c73a4d33b1a4ff2fb08cf40ac42bb968e52f7ae4
> SLAVE_S15: 
> SLAVE_S14: I1016 18:21:03.520972 slave.py:406] [14] sync request from master, downloaded 5 blocks (27 - 31)
> SLAVE_S7: I1016 18:21:03.520896 slave.py:406] [7] sync request from master, downloaded 5 blocks (27 - 31)
> SLAVE_S8: I1016 18:21:03.521011 slave.py:406] [8] sync request from master, downloaded 4 blocks (26 - 29)
> SLAVE_S18: I1016 18:21:03.521023 slave.py:406] [18] sync request from master, downloaded 5 blocks (27 - 31)
> SLAVE_S1: I1016 18:21:03.521154 slave.py:406] [1] sync request from master, downloaded 6 blocks (20 - 25)
> SLAVE_S10: I1016 18:21:03.521264 slave.py:406] [10] sync request from master, downloaded 3 blocks (27 - 29)
> SLAVE_S12: I1016 18:21:03.521490 slave.py:406] [12] sync request from master, downloaded 3 blocks (27 - 29)
> SLAVE_S5: I1016 18:21:03.521558 slave.py:406] [5] sync request from master, downloaded 5 blocks (20 - 24)
> SLAVE_S13: I1016 18:21:03.521574 slave.py:406] [13] sync request from master, downloaded 5 blocks (24 - 28)
> SLAVE_S20: E1016 18:21:03.521722 shard.py:597] Traceback (most recent call last):
> SLAVE_S20: File "/home/laurent_pellegrino/pyquarkchain/quarkchain/cluster/shard.py", line 595, in add_block_list_for_sync
> SLAVE_S20: xshard_list = self.state.add_block(block)
> SLAVE_S20: File "/home/laurent_pellegrino/pyquarkchain/quarkchain/cluster/shard_state.py", line 656, in add_block
> SLAVE_S20: self.__validate_block(block)
> SLAVE_S20: File "/home/laurent_pellegrino/pyquarkchain/quarkchain/cluster/shard_state.py", line 424, in __validate_block
> SLAVE_S20: block.header.hash_prev_minor_block.hex(),
> SLAVE_S20: ValueError: [20] prev block not found, block height 23 prev hash c3f9e52ff0b582e4e330619a92eda0b7fe9a174ab1dcb6ea28f8a7b3d98c9e96

...

> MASTER: E1016 18:21:45.439136 master.py:100] Traceback (most recent call last):
> MASTER: File "master.py", line 98, in sync
> MASTER: await self.__run_sync()
> MASTER: File "master.py", line 156, in __run_sync
> MASTER: await self.__add_block(block)
> MASTER: File "master.py", line 194, in __add_block
> MASTER: await self.master_server.add_root_block(root_block)
> MASTER: File "master.py", line 1015, in add_root_block
> MASTER: check(all([resp.error_code == 0 for _, resp, _ in result_list]))
> MASTER: File "/home/laurent_pellegrino/pyquarkchain/quarkchain/utils.py", line 54, in check
> MASTER: raise AssertionError(msg)
> MASTER: AssertionError
> MASTER: 
> MASTER: I1016 18:21:45.439860 simple_network.py:172] Closing peer 13e8fe6de8394401c91735981ee39f6a4577548aa12cf471ec49fd61837993fd with the following reason:
> MASTER: I1016 18:21:45.440154 simple_network.py:148] Peer 13e8fe6de8394401c91735981ee39f6a4577548aa12cf471ec49fd61837993fd disconnected, remaining 0
> MASTER: I1016 18:21:59.535938 simple_network.py:93] Got HELLO from peer 82384749bb351c8bdbe13645bb0103265e843fbf89bb53e43be915caa1de092c (35.227.54.173:38291)
> MASTER: I1016 18:21:59.571896 simple_network.py:123] Established virtual shard connections with peer 82384749bb351c8bdbe13645bb0103265e843fbf89bb53e43be915caa1de092c
> MASTER: I1016 18:21:59.572502 simple_network.py:132] Peer 82384749bb351c8bdbe13645bb0103265e843fbf89bb53e43be915caa1de092c added to active peer pool

**Comment by qizhou** [comment]
Close since the issue may be stale.  Please re-open if you find the issue again.
