### ISSUE TITLE
master hanging on "write" sys call

### ISSUE THREAD

**Issue by ninjaahhh** [QuarkChain/pyquarkchain#208]
when running the cluster (`testnet201.bootstrap`), after mining for a certain period of time, the jsonrpc server became unresponsive for all requests. `strace` shows following results

```bash
$ ps aux | grep py
...
root     15480  0.3  5.0 2049216 1605800 ?     Sl   Nov20   8:17 pypy3 master.py --cluster_config=/code/cluster_config.json
root     15481  0.8  1.5 788468 484300 ?       Sl   Nov20  22:27 pypy3 slave.py --cluster_config=/code/cluster_config.json --node_id=S0
...
$ sudo strace -p 15480 -s 10000
strace: Process 15480 attached
write(2, "I1121 00:26:53.642705 jsonrpc.py:408] {\"jsonrpc\": \"2.0\", \"method\": \"getWork\", \"params\": [\"0x1\"], \"id\": 433}\n", 108
<ctrl+c>
$ sudo strace -p 15481 -s 10000
strace: Process 15481 attached
epoll_wait(3,
<ctrl+c>
```

so slave server looks fine, but master is hanging on writing the jsonrpc log to strerr (file descriptor 2).

it also points to line 408

https://github.com/QuarkChain/pyquarkchain/blob/5eca86b4bb8459ac8c397443aad76ba31860f940/quarkchain/cluster/jsonrpc.py#L406-L409

where in turn it calls

https://github.com/QuarkChain/pyquarkchain/blob/5eca86b4bb8459ac8c397443aad76ba31860f940/quarkchain/utils.py#L222-L225

need to find out why the `write` call is blocked.

**Comment by ninjaahhh** [comment]
PROGRESS:

doing some searches online 

https://stackoverflow.com/questions/37385755/freeze-when-writing-to-stderr
https://github.com/moby/moby/issues/31540#issuecomment-288729426

and `sudo tail -f /proc/15480/fd/2` helps unblock.

**Comment by qcdll** [comment]
https://github.com/QuarkChain/pyquarkchain/blob/master/quarkchain/cluster/cluster.py#L37
stderr also goes to stdout, and they should all be handled by cluster.py `print_output` and printed to stdout... as we discussed one suspect may be the docker supervisor failing to tail it
