### ISSUE TITLE
progressive sync

### ISSUE THREAD

**Issue by qcdll** [QuarkChain/pyquarkchain#212]
sync takes a long time and the progress cannot be killed halfway and resumed later
we would want this feature for people to join the network easily

**Comment by qcgg** [comment]
if a cluster is killed while syncing, it should be able to resume from the latest root block. it this isn't the case then we have a bug.

**Comment by qcdll** [comment]
tried with my local cluster and it seems to be restarting from the scratch, I will try reproducing this

**Comment by qcdll** [comment]
I was under impression that sync will download both root blocks and minor blocks, but the screenshot suggests otherwise, which is true?
<img width="1110" alt="screen shot 2018-11-28 at 1 45 46 pm" src="https://user-images.githubusercontent.com/40378568/49184449-46f29a80-f314-11e8-95b0-18957f96f8c9.png">

**Comment by qcdll** [comment]
it turns out the stats screenshot was not refreshed correctly, and recent runs with testnet 2.0 show that a sync that was done halfway was written to DB and picked up when restarted
