### ISSUE TITLE
running later without --enable_transaction_history causes cluster to misbehave

### ISSUE THREAD

**Issue by qcdll** [QuarkChain/pyquarkchain#216]
I ran cluster with --enable_transaction_history once, and later ran with the same cluster without the flag. Now the cluster can accept transactions, but the returned tx hash is all 0, like
![screen shot 2018-11-29 at 11 53 45 am](https://user-images.githubusercontent.com/40378568/49248573-e7a59080-f3ce-11e8-9808-6fe72675abe8.png)

this seems an interesting benign bug

**Comment by qcdll** [comment]
all 0 tx hash is also reproducible if I specify wrong network id in transaction:
```
SLAVE_S2: W1129 18:54:33.304244 shard_state.py:285] Failed to add transaction: evm tx network id mismatch. expect 21 but got 3
```

**Comment by ninjaahhh** [comment]
should be a non-issue since our current snapshots all have indexing information.

if this indeed is an issue, clusters using using those snapshots should fail
