### ISSUE TITLE
download too old block when sync 

### ISSUE THREAD

**Issue by chenhuan14** [QuarkChain/pyquarkchain#233]
SLAVE_S1: E1202 12:18:37.594388 shard.py:536] Traceback (most recent call last):
SLAVE_S1: File "/code/pyquarkchain/quarkchain/cluster/shard.py", line 534, in add_block
SLAVE_S1: xshard_list = self.state.add_block(block)
SLAVE_S1: File "/code/pyquarkchain/quarkchain/cluster/shard_state.py", line 655, in add_block
SLAVE_S1: block.header.height, self.header_tip.height
SLAVE_S1: ValueError: block is too old 28 << 4943

**Comment by qcdll** [comment]
this probably means forks at lower height when syncing, should not impact the functionalities of the cluster

**Comment by qcdll** [comment]
normally this won't cause a problem with functionalities of clusters
