### ISSUE TITLE
destroying proxy slave connections

### ISSUE THREAD

**Issue by DreamXzxy** [QuarkChain/pyquarkchain#248]
![image](https://user-images.githubusercontent.com/17998878/49488386-66904280-f881-11e8-9d86-9f30f084c929.png)

**Comment by DreamXzxy** [comment]
![image](https://user-images.githubusercontent.com/17998878/49488521-ec13f280-f881-11e8-8c73-0ad700a0471d.png)

**Comment by qcdll** [comment]
how is this an issue? I don't think master is dead because of destroying proxy slave connections

**Comment by DreamXzxy** [comment]
> how is this an issue? I don't think master is dead because of destroying proxy slave connections

i don't konw, i didn't use VPN.

**Comment by DreamXzxy** [comment]
and the version is testnet2.2.1

**Comment by qcdll** [comment]
doesn't sound a real issue
