### ISSUE TITLE
root高度同步不一致问题 (root block height inconsistency) 

### ISSUE THREAD

**Issue by singlekui** [QuarkChain/pyquarkchain#292]
从testnet2开始，就一直存在这个问题，cluster正常运行一段时间后，就会出现本地高度与bootstrap高度不一样，这样就导致miner挖不出块，虽然cluster表面上看正常运行的，也没报错，最近特别频繁，一晚上cluster挂了四次，每次必须重启cluster才得以解决。

**Comment by ninjaahhh** [comment]
most likely the cluster is trapped in a bad state during syncing. #293 may help in this case.

please report if the problem continues

**Comment by qcdll** [comment]
the issue had been fixed in latest release https://github.com/QuarkChain/pyquarkchain/releases/tag/v2.3.3
