### ISSUE TITLE
[RFC] Implement PoSW

### ISSUE THREAD

**Issue by ninjaahhh** [QuarkChain/pyquarkchain#306]
a quick eng doc on planned implementation for [Proof of Staked Work](https://medium.com/quarkchain-official/proof-of-staked-work-ef36f9499279) (PoSW) on pyquarkchain.

******

for details on parameter definition please check the article linked above.

consensus parameters:

1. `posw_alpha`: the coefficient for calculating effective hash power
1. `posw_beta`: block difficulty multiplier if already produced enough blocks
1. `posw_window_size`: block range for estimating effective hashpower percentage
1. (temporary and testnet only) `posw_total_stakes`: for simplicity, will assume the amount of total stakes is a constant. a more reasonable version is a constant about the number of stakes needed to produce one block in the window.

UPDATE: combine alpha and total stakes to one param.

extra notes:

1. to better test this new consensus algo, may adopt different parameters in different shards so that we can observe different behaviors to further help parameter tuning
******
consensus control flow change:

i. on validating tx

fail a tx in VM level if the tx.sender is not allowed

ii. on validating block

1. when a new block is going to be added, look up previous `posw_window_size` blocks, count how many blocks are produced by the current block's coinbase address (`produced_blocks`)
1. count amount of tokens in the coinbase address (`stake`), calculate `stake_ratio = min(stake / posw_total_stakes, 1)`,
    1. if `produced_blocks / posw_window_size <= stake_ratio * posw_alpha`, accept the block
    2. otherwise the effective difficulty should be multiplied by `posw_beta`, and if the block nonce doesn't meet the requirement, reject the block; otherwise accept the block

**Comment by qizhou** [comment]
4, may be replaced by a constant about the number of stakes needed to produce one block in the window.

**Comment by qcgg** [comment]
`produced_blocks / posw_window_size <= stake_ratio * posw_alpha`?
