### ISSUE TITLE
fatal error: 'secp256k1_ecdh.h' file not found

### ISSUE THREAD

**Issue by kenneth** [QuarkChain/pyquarkchain#316]
```
build/temp.macosx-10.14-x86_64-3.7/_libsecp256k1.c:493:10: fatal error: 'secp256k1_ecdh.h' file not found
#include <secp256k1_ecdh.h>
         ^~~~~~~~~~~~~~~~~~
1 error generated.
error: Setup script exited with error: command 'clang' failed with exit status 1
```

**Comment by qcdll** [comment]
can you let us know how this was encountered? are you trying to run cluster?

A sure and fast way to run cluster is to use the official docker image: 
https://github.com/QuarkChain/pyquarkchain/wiki/Run-a-Private-Cluster-on-the-QuarkChain-Testnet-2.0
https://github.com/QuarkChain/pyquarkchain/releases
