### ISSUE TITLE
Add mining functions

### ISSUE THREAD

**Issue by qcgg** [QuarkChain/pyquarkchain#34]
Add ethash, sha3sha3 to `cluster/miner.py`.
The specific mining function for each shard can be configured through `ShardConfig` in `config.py`
Block validation function shall be updated accordingly.

**Comment by ninjaahhh** [comment]
two extra endpoints to implement (mining algorithm agnostic)

`getWork`: () -> [header hash, block number, difficulty]
`submitWork`: (header hash, nonce, mix digest) -> bool

**Comment by ninjaahhh** [comment]
close this in favor of #105
