### ISSUE TITLE
[RFC] Improve x-shard tx processing

### ISSUE THREAD

**Issue by ninjaahhh** [QuarkChain/pyquarkchain#345]
a quick eng doc on improving how x-shard tx is handled in shard chains.

******

# overview
when a shard receives a new root block, it will read the accompanying x-shard deposits and credit addresses accordingly. the current implementation has two aspects that we want to improve:

1. the throttling is done when sending x-shard tx, where we a) check whether the source and target shards are [neighbors](https://github.com/QuarkChain/pyquarkchain/wiki/Cross-Shard-Transaction#neighbor); b) and use [some heuristics](https://github.com/QuarkChain/pyquarkchain/wiki/Cross-Shard-Transaction#throttling) to limit number of those x-shard tx
2. when the target shard receives those deposits, it will process *all* of them

the drawbacks:

1. number of x-shard tx between shards is very limited in each block (in [this calculation](https://github.com/QuarkChain/pyquarkchain/wiki/Cross-Shard-Transaction#throttling) the number is 3)
2. if we want to support x-shard contract execution, running *all* those x-shard tx in the target shard could be very costly and expose certain DoS vulnerabilities

thus another approach is proposed

1. remove throttling when sending x-shard tx
2. when target shard receives those x-shard tx, process them in a round-robin fashion with a limit on gas, where unfinished tx can be picked up in the next shard block. the round-robin happens for different source shards

# implementation

two extra fields are needed in shard blocks, `xshard_processed_root_block_header` and `xshard_processed_tx_index`, and `xshard_gas_limit` be in the config. following describes the procedure when a shard wants to add a new shard block, where x-shard tx should be handled:

1. read `xshard_processed_root_block_header` and `xshard_processed_tx_index`, load the corresponding x-shard txs 
1. sort the corresponding x-shard tx to a  round-robin list as like `[tx_from_shrad_1, tx_from_shard_2, ...]`
1. starting from tx at `xshard_processed_tx_index + 1`, process those tx under `xshard_gas_limit`. if all the x-shard tx have been processed, advance to the next root block

implementation note: alternative is to have two indices, `minor_header_index` and `xshard_deposit_index`, which serves the same purpose as `xshard_processed_tx_index` but the lookup would be more efficient without iterating the whole x-shard deposit set. downside is one more field in header.

# reference

[spec with pseudocode](https://docs.google.com/document/d/1446Fy0oiWFYKt1sxrKWLyVkx0lqXOPDGqFW6pzFUDpI/edit#)

**Comment by qizhou** [comment]
Should we close this issue as it is fixed by #350 ?

**Comment by ninjaahhh** [comment]
closed by #350
