### ISSUE TITLE
Monitor account balance does not initially work

### ISSUE THREAD

**Issue by Art55555** [QuarkChain/pyquarkchain#349]
In testnet 2.4.0 monitor account balance in the cluster does not initially work in command line. Is it planned to fix this?

**Comment by Art55555** [comment]
root@a2ec2b39e053:/code/pyquarkchain/quarkchain/tools# python3 stats -i 5 -a 0x3561d6C2A3d8A44851A5f43f759C8A9eAFE55edb35d8f49e --ip localhost
QuarkChain Cluster Stats

CPU:                2
Memory:             7 GB
IP:                 localhost
Chains:             6
Network Id:         24
Peers:              144.76.94.140:38291, 84.201.137.47:38291, 73.189.177.78:38291, 84.87.21.227:38291, 93.171.242.29:38291, 195.208.136.44:38291, 94.25.229.185:38291, 94.25.229.185:38291, 40.87.121.247:38291, 35.193.165.172:38291, 35.227.120.22:38291, 37.113.46.66:38291, 35.222.75.173:38291, 104.196.25.188:38291, 84.201.140.132:38291, 84.201.141.171:38291, 13.64.107.255:38291, 130.193.41.211:38291, 35.226.218.225:38291, 178.159.237.90:38291, 178.150.97.249:38291, 220.239.71.150:38291, 35.231.78.227:38291, 35.222.237.86:38291, 158.140.159.38:38291

Querying balances for 0xb16a444c9a0d68f5e9f60e1004091b9f0cda34a9b10d0e9f
Timestamp                         Total    Shards
Traceback (most recent call last):
  File "stats", line 155, in <module>
    main()
  File "stats", line 148, in main
    query_address(public_client, args)
  File "stats", line 105, in query_address
    "getAccountData", address="0x" + address_hex, include_shards=True
  File "/usr/local/lib/python3.6/dist-packages/jsonrpcclient/client.py", line 171, in send
    return self._send_message(request, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/jsonrpcclient/http_client.py", line 82, in _send_message
    log_format='<-- %(message)s (%(http_code)s %(http_reason)s)')
  File "/usr/local/lib/python3.6/dist-packages/jsonrpcclient/client.py", line 114, in _process_response
    response['error'].get('data'))
jsonrpcclient.exceptions.ReceivedErrorResponse: Server error

**Comment by qizhou** [comment]
assigned @qcgg to triage.
