### ISSUE TITLE
Support cross-shard smart contract call

### ISSUE THREAD

**Issue by qizhou** [QuarkChain/pyquarkchain#362]

**Comment by ninjaahhh** [comment]
off the top of my head, those work needs to be done:
1. potentially revise x-shard gas metering?
1. update x-shard tx processing to allow EVM perform contract invocation, where #352 is needed
1. <TODO>

**Comment by ninjaahhh** [comment]
off the top of my head, those work needs to be done:
1. potentially revise x-shard gas metering?
1. update x-shard tx processing to allow EVM perform contract invocation, where #352 is needed
1. \<TODO\>

**Comment by qizhou** [comment]
The code is almost ready, but we need the following tests:
1, gas limit check from the source shard
2, create contract tests
3, update receipts

**Comment by ninjaahhh** [comment]
should close? @qizhou
