### ISSUE TITLE
nonce in header should be biguint

### ISSUE THREAD

**Issue by qizhou** [QuarkChain/pyquarkchain#371]
uint64 seems still to be too small if hash rate is high

**Comment by qcdll** [comment]
is nonce range the search space of mining? 2^64 is already a quite large number to exhaust with reasonable efforts

**Comment by qizhou** [comment]
For ethash it seems enough at the moment (currently difficulty is 2,955,821,438,110,282), but for double sha2, current Bitcoin network has 43 Eh/s (43 * 2^60), which is greater tha 2**64.  Anyway, this is a low priority task, and we probably won't use it at the beginning.

**Comment by qizhou** [comment]
Not going to fix at the moment.
