### ISSUE TITLE
fatal error: 'secp256k1_ecdh.h' file not found

### ISSUE THREAD

**Issue by telnetor** [QuarkChain/pyquarkchain#381]
`pip install -e .`
...
    creating build/temp.macosx-10.14-x86_64-3.6/build
    creating build/temp.macosx-10.14-x86_64-3.6/build/temp.macosx-10.14-x86_64-3.6
    gcc -pthread -arch x86_64 -DNDEBUG -O2 -I/usr/local/opt/openssl/include -fPIC -I/Users/xxxx/virtualenv/qc/include -I/usr/local/Cellar/pypy3/7.0.0/libexec/include -c build/temp.macosx-10.14-x86_64-3.6/_libsecp256k1.c -o build/temp.macosx-10.14-x86_64-3.6/build/temp.macosx-10.14-x86_64-3.6/_libsecp256k1.o
    build/temp.macosx-10.14-x86_64-3.6/_libsecp256k1.c:516:10: fatal error: 'secp256k1_ecdh.h' file not found
    #include <secp256k1_ecdh.h>
             ^~~~~~~~~~~~~~~~~~
    1 error generated.
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/Users/xxxx/virtualenv/qc/bin/pypy3 -u -c "import setuptools, tokenize;__file__='/private/var/folders/cw/l376cv5j3ylg_31jcmh5496c0000gn/T/pip-install-51w7bl5t/coincurve/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/cw/l376cv5j3ylg_31jcmh5496c0000gn/T/pip-record-s4ojx07o/install-record.txt --single-version-externally-managed --compile --install-headers /Users/xxxx/virtualenv/qc/include/site/python3.6/coincurve" failed with error code 1 in /private/var/folders/cw/l376cv5j3ylg_31jcmh5496c0000gn/T/pip-install-51w7bl5t/coincurve/

**Comment by ninjaahhh** [comment]
hope this similar issue can help https://github.com/ethereum/py-evm/issues/1021

**Comment by telnetor** [comment]
I solve it, pip does not install secp256k1 library auto, I download this library and copy missing file to /usr/local/include, and it worked.
https://files.pythonhosted.org/packages/52/62/d7bf3829e126e517e253d2e22a63511c54bbaac34d7ddea316cde040fc49/secp256k1-0.13.2.tar.gz
