### ISSUE TITLE
Cluster shutdown due to memory leak

### ISSUE THREAD

**Issue by jyouyj** [QuarkChain/pyquarkchain#382]
The cluster is shutdown periodically. I think it still has the memory leak problem. I start the cluster yesterday morning, which use about 1.15G memory. When I double check today, it increases to about 2G memory. Since the machine has 15G memory, the cluster can work about two weeks，which matches my observation. Noted that I use the python version instead of pypy3.

**Comment by qcdll** [comment]
can you try using https://github.com/QuarkChain/pyquarkchain/pull/254 to quantify the problem?

**Comment by ninjaahhh** [comment]
#261 also has some context

**Comment by jyouyj** [comment]
The log error is shown as follow,

MASTER: OSError: [Errno 24] Too many open files
MASTER: E0311 18:22:54.645542 base_events.py:1274] socket.accept() out of system resource
MASTER: socket: <socket.socket fd=22, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('0.0.0.0', 38291)>
MASTER: Traceback (most recent call last):
MASTER: File "/usr/lib/python3.6/asyncio/selector_events.py", line 179, in _accept_connection
MASTER: conn, addr = sock.accept()
MASTER: File "/usr/lib/python3.6/socket.py", line 205, in accept
MASTER: fd, addr = self._accept()
MASTER: OSError: [Errno 24] Too many open files
MASTER: E0311 18:22:54.645673 base_events.py:1274] socket.accept() out of system resource
MASTER: socket: <socket.socket fd=22, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('0.0.0.0', 38291)>
MASTER: Traceback (most recent call last):
MASTER: File "/usr/lib/python3.6/asyncio/selector_events.py", line 179, in _accept_connection
MASTER: conn, addr = sock.accept()
MASTER: File "/usr/lib/python3.6/socket.py", line 205, in accept
MASTER: fd, addr = self._accept()
MASTER: OSError: [Errno 24] Too many open files
MASTER: E0311 18:22:54.645813 base_events.py:1274] socket.accept() out of system resource
MASTER: socket: <socket.socket fd=22, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('0.0.0.0', 38291)>
MASTER: Traceback (most recent call last):
MASTER: File "/usr/lib/python3.6/asyncio/selector_events.py", line 179, in _accept_connection
MASTER: conn, addr = sock.accept()
MASTER: File "/usr/lib/python3.6/socket.py", line 205, in accept
MASTER: fd, addr = self._accept()
MASTER: OSError: [Errno 24] Too many open files
MASTER: E0311 18:22:54.645943 base_events.py:1274] socket.accept() out of system resource
MASTER: socket: <socket.socket fd=22, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('0.0.0.0', 38291)>
MASTER: Traceback (most recent call last):
MASTER: File "/usr/lib/python3.6/asyncio/selector_events.py", line 179, in _accept_connection
MASTER: conn, addr = sock.accept()
MASTER: File "/usr/lib/python3.6/socket.py", line 205, in accept
MASTER: fd, addr = self._accept()
MASTER: OSError: [Errno 24] Too many open files
MASTER: E0311 18:22:54.646073 base_events.py:1274] socket.accept() out of system resource
MASTER: socket: <socket.socket fd=22, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('0.0.0.0', 38291)>
MASTER: Traceback (most recent call last):
MASTER: File "/usr/lib/python3.6/asyncio/selector_events.py", line 179, in _accept_connection
MASTER: conn, addr = sock.accept()
MASTER: File "/usr/lib/python3.6/socket.py", line 205, in accept
MASTER: fd, addr = self._accept()
MASTER: OSError: [Errno 24] Too many open files
MASTER: E0311 18:22:54.646232 base_events.py:1274] socket.accept() out of system resource
MASTER: socket: <socket.socket fd=22, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('0.0.0.0', 38291)>
MASTER: Traceback (most recent call last):
MASTER: File "/usr/lib/python3.6/asyncio/selector_events.py", line 179, in _accept_connection
MASTER: conn, addr = sock.accept()
MASTER: File "/usr/lib/python3.6/socket.py", line 205, in accept
MASTER: fd, addr = self._accept()
MASTER: OSError: [Errno 24] Too many open files
MASTER: E0311 18:22:54.646365 base_events.py:1274] socket.accept() out of system resource
MASTER: socket: <socket.socket fd=22, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('0.0.0.0', 38291)>
MASTER: Traceback (most recent call last):
MASTER: File "/usr/lib/python3.6/asyncio/selector_events.py", line 179, in _accept_connection
MASTER: conn, addr = sock.accept()
MASTER: File "/usr/lib/python3.6/socket.py", line 205, in accept
MASTER: fd, addr = self._accept()
MASTER: OSError: [Errno 24] Too many open files
MASTER: E0311 18:22:54.646498 base_events.py:1274] socket.accept() out of system resource
MASTER: socket: <socket.socket fd=22, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('0.0.0.0', 38291)>
MASTER: Traceback (most recent call last):
MASTER: File "/usr/lib/python3.6/asyncio/selector_events.py", line 179, in _accept_connection
MASTER: conn, addr = sock.accept()
MASTER: File "/usr/lib/python3.6/socket.py", line 205, in accept
MASTER: fd, addr = self._accept()
MASTER: OSError: [Errno 24] Too many open files
MASTER: E0311 18:22:54.646631 base_events.py:1274] socket.accept() out of system resource
MASTER: socket: <socket.socket fd=22, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('0.0.0.0', 38291)>
MASTER: Traceback (most recent call last):
MASTER: File "/usr/lib/python3.6/asyncio/selector_events.py", line 179, in _accept_connection
MASTER: conn, addr = sock.accept()
MASTER: File "/usr/lib/python3.6/socket.py", line 205, in accept
MASTER: fd, addr = self._accept()
MASTER: OSError: [Errno 24]
