### ISSUE TITLE
new_block_pool 未及时清理，可能会引发DOS攻击

### ISSUE THREAD

**Issue by BubbLess** [QuarkChain/pyquarkchain#387]
注意到在shard.py中未对new_block_pool做及时的清理，在add_block函数中的逻辑如下
```
        try:
            xshard_list, coinbase_amount_map = self.state.add_block(block)
        except Exception as e:
            Logger.error_exception()
            return False

        # only remove from pool if the block successfully added to state,
        #   this may cache failed blocks but prevents them being broadcasted more than needed
        # TODO add ttl to blocks in new_block_pool
        self.state.new_block_pool.pop(block.header.get_hash(), None)
```
在state中add_block若失败则直接返回，new_block_pool中的失败区块却没有进行清理，这样它们将持续堆积在内存中。
从攻击者角度上讲我们可以构造大量的恶意区块，它们无法通过state.add_block中的验证，但却会被添加进new_block_pool中，对节点的内存进行DOS攻击。不过在添加进new_block_pool之前会对该区块的工作量进行检查，这样就需要我们耗费一定的资源，但是因为在接收区块时并未对高度进行限制，那么我们可以从区块高度非常低时在同一高度生成大量区块，此时需要的难度较低，而且这样正常流程生成的区块本身也会在state.add_block中失败，满足了我们的要求。另外此处的validate_seal函数似乎并未对diff进行检查，只是一个简单估计，应该可以直接将diff调整到最小值，这样也可以生成大量恶意区块。利用这些区块即可对目标节点的内存进行DOS攻击。

**Comment by qizhou** [comment]
new_block_pool 的所有block需要通过difficulty测试，所以构造大量恶意的区块的难度应该很高？

**Comment by qizhou** [comment]
这里有个问题是difficulty测试，没有测试parent的difficulty。

**Comment by qcdll** [comment]
1. we should check difficulty number is correct
2. we can discard blocks that are much shorter than tip when broadcasting

**Comment by ninjaahhh** [comment]
keep it open since it's still possible to spam the new block pool with failed blocks (though it does require more hash power than before)

**Comment by ninjaahhh** [comment]
#560 should further help this issue since full validation is required before adding to the new block pool. 

now the only chance for new block pool keeping blocks would be passing the validation AND failing adding to local chain, which should happen rarely. 

but the DoS attacking vector should be gone.
