### ISSUE TITLE
私有json rpc暴露风险

### ISSUE THREAD

**Issue by kakatototata** [QuarkChain/pyquarkchain#394]
在 cluster/jsonrpc.py ⽂件中定义了⼀系列 API，有 public 和 private 两种。
**Public API**
```python
...
    @public_methods.add
    async def sendTransaction(self, data):
        def get_data_default(key, decoder, default=None):
            if key in data:
                return decoder(data[key])
            return default
...
```
**Private API**
```python
...
    @private_methods.add
    async def getStats(self):
        # This JRPC doesn't follow the standard encoding
        return await self.master.get_stats()
...
```
由于在配置⽂件中**没有明确绑定 IP 地址**，**Public 与 Private 会绑定到同⼀个IP 地址**上，这导致 Private API 对外暴露。在以往案例中，Ethereum 曾因私有 API 暴露发⽣盗币事件。在本案例中，攻击者可以通过本漏洞操作矿机，包括关停、DDoS 等。

**建议**:
增加 IP 绑定、⽤户名密码等访问控制

**Comment by qizhou** [comment]
Should be fixed by #422

**Comment by jyouyj** [comment]
We fix this problem by disabling public and private json rpc by default value localhost. https://github.com/QuarkChain/pyquarkchain/pull/426
