### ISSUE TITLE
不可靠的随机数实现

### ISSUE THREAD

**Issue by kakatototata** [QuarkChain/pyquarkchain#396]
## 不可靠的随机数实现
本项目中使用了`random`作为密码算法的随机数发⽣器，`random`库不满足工业级的密码学算法需求，建议更换。

**建议**：使用`os.urandom`实现

**Comment by qizhou** [comment]
I would suggest putting these two issues separately for better tracking.  Thanks.

**Comment by qcdll** [comment]
pls provide concrete examples

**Comment by qizhou** [comment]
random should be used for non-cryptographic use.  If you find the usage of random to generate cryptographic-level random numbers, please let us know.  Thanks.

**Comment by kakatototata** [comment]
We recommend that in order to avoid potential security issues, even non-algorithmic purposes, we'd better using a stronger random number generation algorithm.

**Comment by qcdll** [comment]
@kakatototata can you please provide specific examples in our code base? specifically, which part do you think should benefit from a stronger random generation algorithm?

**Comment by qizhou** [comment]
Close because of stale issue.
