### ISSUE TITLE
恶意构造request导致asyncio.streams因处理数据量过大崩溃

### ISSUE THREAD

**Issue by Guy1m0** [QuarkChain/pyquarkchain#415]
因为rpc端口对于request没有做任何检查，并且self.counter对于并未register的method_name也忠实的进行记录:
```python=
async def _handle(self, request):
    ...
    try:
        d = json.loads(request)
    except Exception:
        pass
    method = d.get("method","null")
    if method in self.counters:
        self.counters[method] += 1
    else:
        self.counters[method] = 1
```
导致可以恶意构造一个method_name为足够长的string，测试中为100000的长度string *m*。

```shell=
curl http://localhost:38391 -X POST --data '{"jsonrpc": "2.0", "method": m, "id": 1}'
```
当server成功接收这一条rpc call的时候再调用
```shell=
curl http://localhost:38391 -X POST --data '{"jsonrpc": "2.0", "method": "getJrpcCalls",  "id": 1}'
```
如下图所示，server崩溃，并拒绝任意其他rpc call
![Screen Shot 2019-03-18 at 10 55 07 PM](https://user-images.githubusercontent.com/6608956/54588041-c8ee0700-4a5c-11e9-9c7a-1b5b22c2c8c7.png)

**Comment by qizhou** [comment]
跟#416 同理，因为json rpc不是一个公开的p2p协议，对json rpc的恶意攻击的理论概率比较低。

**Comment by kingdomyi** [comment]
> 跟#416 同理，因为json rpc不是一个公开的p2p协议，对json rpc的恶意攻击的理论概率比较低。

我们测试发现，依然可以从非本地地址对目标ip地址通过端口38391实施以上攻击。

**Comment by qizhou** [comment]
As I mentioned before, json rpc is not designed for public use.  We will disable json rpc by default (see #422). Enabling json rpc implies that the user has already setup proper access control.

**Comment by jyouyj** [comment]
We fix this problem by disabling public and private json rpc by default value localhost. https://github.com/QuarkChain/pyquarkchain/pull/426
