### ISSUE TITLE
构造大量无效不重复method RPC call导致本地counter撑爆

### ISSUE THREAD

**Issue by Guy1m0** [QuarkChain/pyquarkchain#416]
因为rpc端口对于request没有做任何检查，并且counter对于并未register的method_name也忠实的进行记录:
```python=
async def _handle(self, request):
    ...
    try:
        d = json.loads(request)
    except Exception:
        pass
    method = d.get("method","null")
    if method in self.counters:
        self.counters[method] += 1
    else:
        self.counters[method] = 1
```
因此，可以随机生成大量不重复的method_name *m*，并对于每一个*m*，通过如下RPC CALL：
```shell=
curl http://localhost:38391 -X POST --data '{"jsonrpc": "2.0", "method": m, "id": 1}'
```
导致本地self.counters保存大量无效key-value，最终撑爆内存。我们测试了一下5个小时可以占用内存及虚拟内存近50G空间
![51d0c068-1a7f-4581-94aa-e308f1676d94](https://user-images.githubusercontent.com/6608956/54614390-4898c780-4a97-11e9-89d7-91059f1aa4b6.png)

**Comment by qizhou** [comment]
JSON rpc 我记得我们默认不公开的

**Comment by kingdomyi** [comment]
> JSON rpc 我记得我们默认不公开的

我们测试发现，依然可以从非本地地址对目标ip地址通过端口38391实施以上攻击。

**Comment by qizhou** [comment]
As I mentioned before, json rpc is not designed for public use.  We will disable json rpc by default (see #422). Enabling json rpc implies that the user has already setup proper access control.

**Comment by jyouyj** [comment]
We fix this problem by disabling public and private json rpc by default value localhost. https://github.com/QuarkChain/pyquarkchain/pull/426
