### ISSUE TITLE
Contract creation inside contract may fail when lacking full shard ID

### ISSUE THREAD

**Issue by ninjaahhh** [QuarkChain/pyquarkchain#419]
@516108736 can you add the failed test case from go-ethereum?

**Comment by 516108736** [comment]
测试case就是master上的 [case](https://github.com/QuarkChain/pyquarkchain/tree/master/fixtures/GeneralStateTests)
1.咱们py程序跑这些case时是打了补丁，所有没有暴露出问题，所有问题复现时别打补丁
2.关于这个抛出异常的case大概有20个，都在上面这个link里，我列举出一个吧 [例子](https://github.com/QuarkChain/pyquarkchain/blob/master/fixtures/GeneralStateTests/stCallCodes/callcodeDynamicCode.json)

**Comment by 516108736** [comment]
测试用的是v2.3.3，为了成功跑case，做了一点改动，

`root@9808a00fbe87:/code/pyquarkchain/quarkchain/evm/tests# git diff
diff --git a/quarkchain/evm/tests/new_statetest_utils.py b/quarkchain/evm/tests/new_statetest_utils.py
index f9a2b57..3418fda 100644
--- a/quarkchain/evm/tests/new_statetest_utils.py
+++ b/quarkchain/evm/tests/new_statetest_utils.py
@@ -100,7 +100,8 @@ def compute_state_test_unit(state, txdata, indices, konfig):
             tx._in_mutable_context = False
         # Run it
         prev = state.to_dict()
-        success, output = apply_transaction(state, tx)
+        tx.set_shard_size(1)
+        success, output = apply_transaction(state, tx,tx.hash)
         print("Applied tx")
     except InvalidTransaction as e:
         print("Exception: %r" % e)
`

而且把hash对比抛出异常删掉，（因为我的目的是生成新的hash作为标准答案，用go版本修改过的代码来跑这些case来对比这些标准答案）

**Comment by ninjaahhh** [comment]
fixed by #643

**Comment by ninjaahhh** [comment]
reopen since another problem is if creating contracts via CALL family, full shard key will still be lacking, thus the address formulation will fall back to old ethereum style. we need to pass full shard key to every message in VM
