### ISSUE TITLE
Make sure can't sync between different network IDs

### ISSUE THREAD

**Issue by ninjaahhh** [QuarkChain/pyquarkchain#420]

**Comment by jyouyj** [comment]
We can try to include the network ID information into the genesis block.

**Comment by qizhou** [comment]
This won't help, right?  As the genesis blocks of different network id's should be different?

**Comment by qizhou** [comment]
The first command is HelloCommand, which contains network id.  If network id differs, the connection should be closed automatically.

**Comment by qizhou** [comment]
Verified by running two nodes with different network id's and that they will disconnect after HelloCommand.
