### ISSUE TITLE
shard.py should use total difficulty to check best observed root block instead of height

### ISSUE THREAD

**Issue by qizhou** [QuarkChain/pyquarkchain#421]
Example code:

https://github.com/QuarkChain/pyquarkchain/blob/3f26e929f794cd722f2c736f1cab4aab7019e42c/quarkchain/cluster/shard.py#L148-L149

https://github.com/QuarkChain/pyquarkchain/blob/3f26e929f794cd722f2c736f1cab4aab7019e42c/quarkchain/cluster/shard.py#L158-L159

https://github.com/QuarkChain/pyquarkchain/blob/3f26e929f794cd722f2c736f1cab4aab7019e42c/quarkchain/cluster/shard.py#L67-L68

**Comment by ninjaahhh** [comment]
can you take a look at this? @jyouyj
