### ISSUE TITLE
CORS:在默认的HTTP RPC里允许所有域

### ISSUE THREAD

**Issue by telnetor** [QuarkChain/pyquarkchain#423]
这个问题会有潜在的来自web浏览器的钓鱼攻击风险，建议显式配置可访问域。
另外RPC接口默认暴露端口在0.0.0.0下，会受到来自公网的攻击，建议默认监听在内网或者本地网络。

**Comment by qcdll** [comment]
is this same as #422?

**Comment by jyouyj** [comment]
We fix this problem by disabling public and private json rpc by default value localhost. https://github.com/QuarkChain/pyquarkchain/pull/426
