### ISSUE TITLE
sendTransaction 统一传参格式

### ISSUE THREAD

**Issue by Guy1m0** [QuarkChain/pyquarkchain#425]
在 jsonrpc.py L659中 **data** 变量，传参格式错误，导致对于相应的RPC Call都会造成**Invalid params**错误

```python=
    @public_methods.add
    async def sendTransaction(self, data):
        def get_data_default(key, decoder, default=None):
            if key in data:
                return decoder(data[key])
            return default
```

正确的写法应为 **\*\*data**

**Comment by qizhou** [comment]
test_jsonrpc.py 有 test_sendTransaction测试，并且可以通过。

**Comment by qizhou** [comment]
@jyouyj will use a live machine to reproduce the problem.

**Comment by ninjaahhh** [comment]
hmm, following curl seems to work fine.

```
curl -X POST -H "Content-Type: application/json" 54.191.146.154:38391 -d '{
  "jsonrpc": "2.0",
  "params": [{
    "nonce": "0x0",
    "gasPrice": "0x0",
    "gas": "0x7530",
    "value": "0x0",
    "data": "0x",
    "fromFullShardId": "0x00033092",
    "toFullShardId": "0x00033092",
    "networkId": "0x19",
    "to": "0x3b65b822a40565ed02f8301a332b6792ce3dd335",
    "v": "0x1b",
    "r": "0x293d59ef8705e34585d646f5899530d54a2d39b312fd061607036152e5fcf580",
    "s": "0x098d2e479720cee2be565703dd97085765adc65b18ed8d9dfbf3d6d7e7fe556e",
    "gasTokenId": "0x8bb0",
    "transferTokenId": "0x8bb0"
  }],
  "method": "sendTransaction",
  "id": 1
}'
```

@Guy1m0 can you make sure you are making a correct JSONRPC request?

**Comment by Guy1m0** [comment]
> hmm, following curl seems to work fine.
> 
> ```
> curl -X POST -H "Content-Type: application/json" 54.191.146.154:38391 -d '{
>   "jsonrpc": "2.0",
>   "params": [{
>     "nonce": "0x0",
>     "gasPrice": "0x0",
>     "gas": "0x7530",
>     "value": "0x0",
>     "data": "0x",
>     "fromFullShardId": "0x00033092",
>     "toFullShardId": "0x00033092",
>     "networkId": "0x19",
>     "to": "0x3b65b822a40565ed02f8301a332b6792ce3dd335",
>     "v": "0x1b",
>     "r": "0x293d59ef8705e34585d646f5899530d54a2d39b312fd061607036152e5fcf580",
>     "s": "0x098d2e479720cee2be565703dd97085765adc65b18ed8d9dfbf3d6d7e7fe556e",
>     "gasTokenId": "0x8bb0",
>     "transferTokenId": "0x8bb0"
>   }],
>   "method": "sendTransaction",
>   "id": 1
> }'
> ```
> @Guy1m0 can you make sure you are making a correct JSONRPC request?

Hi, I follow the instruction from the [link](https://developers.quarkchain.io/#sendtransaction). The example provided without including '[' ']' for the 'params', so it will cause the 'invlid param' error. And you can also find out that the method 'sendUnigedTransaction" is almost identical to the method 'sendTransaction' but the param format, which is used '**data' not 'data'.

**Comment by ninjaahhh** [comment]
@Guy1m0  thanks for pointing out. we probably will deprecate `sendUnsigedTransaction`. for the `params` format, we want to stay consistent with [the ethereum style](https://github.com/ethereum/wiki/wiki/JSON-RPC#example-22), where the parameters are always passed as a list.

but we will need to double check endpoints like `estimateGas` or `call` to make sure we have a consistent parameter passing style.

**Comment by ninjaahhh** [comment]
lower the priority
