### ISSUE TITLE
change discovery format to be different from eth

### ISSUE THREAD

**Issue by qcdll** [QuarkChain/pyquarkchain#434]
an attack was possible because of using same format as eth to perform discovery (the incident lead to #432; some background read: https://github.com/ethereum/devp2p/wiki/Discovery-Overview#capability)

Despite we adding blacklisting, we should fix the problem at lower level. We should to use different format to prevent eth nodes from being added to quarkchain routing table

eth has this problem as well and tries to solve it using discv5, we may want to look into that as well

**Comment by qizhou** [comment]
Nice!  We should high prioritize this enhancement - hopefully we could test it with our testnet before mainnet launch.
