### ISSUE TITLE
DNS rebinding攻击风险

### ISSUE THREAD

**Issue by BubbLess** [QuarkChain/pyquarkchain#437]
json rpc目前默认开在本地，但是并没有做DNS rebinding攻击的防范，比如下面的请求
![](https://raw.githubusercontent.com/BubbLess/myimg/master/20190325115252.png)
攻击者利用DNS rebinding攻击可以从受害者浏览器发动对本地rpc的攻击，这样请求速度可以非常高，这样可以与前面的几个rpc dos的问题相结合，#415 与 #416 
建议检查请求头中的HOST字段，拒绝localhost及本地ip外的请求

**Comment by jyouyj** [comment]
The default json rpc port is set to 127.0.0.1. The user should open the port manually.
