### ISSUE TITLE
过高的gas消耗

### ISSUE THREAD

**Issue by kakatototata** [QuarkChain/pyquarkchain#439]
当执行交易时，由于分片机制，会导致在不同分片的账户之间需要进行跨分片交易通知，这里的跨分片通信 gas 为 9000：
```python
...
GCALLVALUETRANSFER = 9000   # non-zero-valued call
GLOGBYTE = 8          # cost of a byte of logdata

GTXXSHARDCOST = GCALLVALUETRANSFER      # x-shard tx deposit gas
...
```
相比于以太坊，由于有额外的跨分片交易的 gas支出，因此当 `gasLimit` 过低且跨分片交易过多时（如合约中批量转账），更容易出现 `gasLimit` 不足无法打包的现象。但是过低的跨分片交易 gas 可能又会导致恶意阻塞分片的情景。

**建议**：进行跨分片通信gas值的合理性测试。

**Comment by qizhou** [comment]
close the issue since it is intended design.
