### ISSUE TITLE
潜在的算力攻击

### ISSUE THREAD

**Issue by kakatototata** [QuarkChain/pyquarkchain#440]
算力分配为主链算力至少在 50% 以上，这样可以?定程度上避免算力攻击，但是前提是主链 50% 算力必须得到保证，在白皮书和代码中没有找到相关的具体措施。当主链上算力不足的时候，容易导致 51% 攻击。

**建议**: 给主链更高的区块难度以及代币奖励，并且根据两层的算力比例进行动态调整。同时也可以在网络层面避免分片层和根链层的算力失衡。

**Comment by jyouyj** [comment]
我们用代币经济学模型来确保有足够的算力维护我们主链的安全。以下是我们发表的相应文章https://medium.com/quarkchain-official/part-5-collaborative-mining-and-hashpower-reuse-technique-79a3ade61a9a
