### ISSUE TITLE
handle_get_minor_block_header_list_request中 limit 未限制导致的DOS问题

### ISSUE THREAD

**Issue by BubbLess** [QuarkChain/pyquarkchain#441]
在shard.py的handle_get_minor_block_header_list_request函数中，没有对limit作上限的限制，如下
```
    async def handle_get_minor_block_header_list_request(self, request):
        if request.branch != self.shard_state.branch:
            self.close_with_error("Wrong branch from peer")
        if request.limit <= 0:
            self.close_with_error("Bad limit")
        # TODO: support tip direction
        if request.direction != Direction.GENESIS:
            self.close_with_error("Bad direction")

        block_hash = request.block_hash
        header_list = []
        for i in range(request.limit):
            header = self.shard_state.db.get_minor_block_header_by_hash(
                block_hash, consistency_check=False
            )
            header_list.append(header)
            if header.height == 0:
                break
            block_hash = header.hash_prev_minor_block

        return GetMinorBlockHeaderListResponse(
            self.shard_state.root_tip, self.shard_state.header_tip, header_list
        )
```
当传入的limit较大时，其中的header_list将不断增大，从而填充内存空间，最终可能导致内存崩溃。
而此处的request是通过p2p发送，所以我们可以作为攻击节点给目标节点发送请求攻击对应shard的slave服务器，此处我也在本地做了简单的尝试，不过因为本地并没有足够的区块，所以便没有每次向前取区块，真正攻击可能需要网络上线几个月后有足够的区块才行。
当发送limit为100万左右时，大概一分钟后内存占用如下，而且对应的处理线程会卡住
![](https://raw.githubusercontent.com/BubbLess/myimg/master/20190328202550.png)
内存占用增长的很快，如果我们进一步增大limit的话，后果就更可怕了
![](https://raw.githubusercontent.com/BubbLess/myimg/master/20190328202719.png)
造成的内存压力很大
![](https://raw.githubusercontent.com/BubbLess/myimg/master/20190328202757.png)
建议对 request 中的 limit 设置上限。

**Comment by BubbLess** [comment]
另外因为对root_block_header的处理逻辑也是一样的，只不过rootchain的出块速度较慢，所以要形成威胁需要等待时间较久，建议也一并修复

**Comment by qcdll** [comment]
while fixing this, I am wondering how you requested 1 million minor blocks when the loop is just going to break when `height == 0`:
https://github.com/QuarkChain/pyquarkchain/blob/6a66a11ad48835163a20b3b06ed3ff59a35dde11/quarkchain/cluster/shard.py#L115

**Comment by BubbLess** [comment]
我在上面提到因为本地没有足够的区块，所以我在本地测试时去掉了这一句
```
block_hash = header.hash_prev_minor_block
```
因此攻击形成威胁可能要在网络运行几个月后。

**Comment by qcdll** [comment]
This has been fixed
