### ISSUE TITLE
Bootstrap Nodes falling to wrong Root block

### ISSUE THREAD

**Issue by Bambarello** [QuarkChain/pyquarkchain#447]
Looking to stats of one of 3 bootstrap nodes, particularly: 35.155.213.180:38291
It looks like this node is constantly (every 5-10 seconds) is showing wrong root block and only one shard. This is causing major sync issues for new nodes.

![image](https://user-images.githubusercontent.com/33266159/55288091-266a4800-53bb-11e9-8cb7-3bafd19391ec.png)

The nodes IPs checked from config file:
"BOOT_NODES": "enode://f2b808fa11e695a26489e21143b7a4e4012bae1fbbbdb4adfb72627ac591f93490c393f4a59acd7bb18a01e1a289830e5020bf6976abf3071de628be74974cce@34.215.81.118:38291,enode://5eeaae0986bb6d7e36fd3a23ae15ca371ba9e88e8545825ed587a472b5ec417c3f757ee46e643d834a7ff454855cfc28b736b8b76f2eae3ebbe61028b777971c@35.155.213.180:38291,enode://7e6a535da88c368cc47d9d6a3fc76d92aa7d3537ed66161c7dc3b6801de48d4a23ed6c8b48053b64faf715a77ec097d624c8638269dcd9339935194b7f3c3530@52.38.218.246:38291",

**Comment by Bambarello** [comment]
This bootstrap node is also showing wrong Miner Stats - stucked at 24017

![image](https://user-images.githubusercontent.com/33266159/55288110-7a752c80-53bb-11e9-88df-70ddc0e7917f.png)

**Comment by qcdll** [comment]
Please note, that bootnodes helps in the discovery process, which is for new nodes to *discover* peers in the quarkchain network, and bootnodes do not necessary accept p2p connections (why would they)

That said, I don't think "This is causing major sync issues for new nodes" is of any connection to whatever issue that a particular bootnode is having with syncing

**Comment by Bambarello** [comment]
Ok, thanks, so maybe the root cause of sync issues is something else.
