### ISSUE TITLE
cluster_peer_id is too short

### ISSUE THREAD

**Issue by xhyumiracle** [QuarkChain/pyquarkchain#448]
When master receives a request from peer and forwards it to slaves, it rounds the cluster_peer_id to 64 bits:
```python
    def __init__(self, quark_peer: QuarkPeer):
        cluster_peer_id = quark_peer.remote.id % 2 ** 64
        super().__init__(
            ...
            cluster_peer_id=cluster_peer_id,
            ...
        )
        self.quark_peer = quark_peer
```
Then in get_connection_to_forward:
```python
    def get_connection_to_forward(self, metadata):
        """ Override ProxyConnection.get_connection_to_forward()
        """
        if metadata.cluster_peer_id == 0: 
            # RPC from master
            return None
```
In the slave side, if metadata.cluster_peer_id == 0, this request would be processed with MasterConnection.

Thus if one could generate a peer with all the lower 64 bits of 'id' be 0, it could forge any Master request and send it to any cluster, when the Master forwards it to Slaves, they'll treat it as it's from Master server. It can control slaves to connect to any other ip as slave or peers, stop/start mining, execute any traction, or even utilize malformed packet to crash the whole cluster.

Speaking of 'id':
```python
class Node:
    def __init__(self, pubkey: datatypes.PublicKey, address: Address) -> None:
        self.pubkey = pubkey
        self.address = address
        self.id = big_endian_to_int(keccak(pubkey.to_bytes()))
```
Although the best one could do might be brute force ec key pairs to find that private key, which could take a long time, but once someone found it, it could control and even destroy any cluster by forging malformed master requests.

The reason it rounds cluster_peer_id to 64 bits is:
```python
class ClusterMetadata(Metadata):
    ...
    FIELDS = [("branch", Branch), ("cluster_peer_id", uint64)]
    ...
```

**Comment by qizhou** [comment]
We need to double check on this @qcdll

**Comment by qizhou** [comment]
Original design imposes that cluster_peer_id is a monotonic increasing 64-bit integer (starting from 1).  Looks like introducing p2p breaks the assumption.  Good find.

**Comment by qcdll** [comment]
goot catch! please see PR for fix, this is a valid concern

**Comment by xhyumiracle** [comment]
Cool, the pr did do the fix. 

I guess you've realized it but just to be clear, 64-bit is still relatively short for peer id. The attacker might gen the key that could 'represent' any peer other than the master, and disconnect the connections between the victim and other peers (or between the target and other victims). 

It might not be a cost-effective attack, but when it targeting the seed node or a fullnode that exchanges relying on, or a powerful mining pool, it's might still worth to launch it (considering eclipse and double spend etc.).

The best fix would be increase the peer id size, or switch to the monotonic increasing pattern.

**Comment by qcdll** [comment]
a few observations:

1. unless jsonrpc service is open (which by itself is a big issue if you run a node and the service is open to the public), it is impossible to know cluster peers
2. we can further prevent duplicate peer ids from being added
3. eclipse attack is a separate topic, and it has been handled by some fixes from trinity (eg. dial out percentage)
4. even with this attack dimension (generating a privkey which yields the same 64-bit peer id for certain clusters in the network), it is impossible to know which peers the node connects to
