### ISSUE TITLE
allow whitelisted address to send transactions while ENABLE_TX_TIMESTAMP is not reached

### ISSUE THREAD

**Issue by qizhou** [QuarkChain/pyquarkchain#449]
We will allow some specific sender to transfer token so that
1, distribute some bounty (such as mining) early
2, allow early token swap for PoSW users
3, etc

**Comment by ninjaahhh** [comment]
@qizhou can you elaborate?

**Comment by qizhou** [comment]
We will allow some specific sender to transfer token so that
1, distribute some bounty (such as mining) early
2, allow early token swap for PoSW users
3, etc
