### ISSUE TITLE
p2p read timeout and ping/pong

### ISSUE THREAD

**Issue by qcdll** [QuarkChain/pyquarkchain#452]
replaces #401 

a few questions/up for discussion:
1. do we need a timeout for p2p read?
https://github.com/QuarkChain/pyquarkchain/blob/33e672242dea2b12745a9cbd26470d23ba18c11f/quarkchain/p2p/p2p_manager.py#L286
2. do we need ping/pong mechanism in p2p protocol? what is the benefit of having them?

**Comment by qcdll** [comment]
cc @qizhou

**Comment by qizhou** [comment]
I think ping/pong in p2p protocol (not discovery) is kind of heartbeat to detect if the peer is dead or alive.   I think we could at least include the command before mainnet so that adding timeout feature won't break p2p protocol.

**Comment by qizhou** [comment]
Reference code: https://github.com/ethereum/go-ethereum/blob/master/p2p/peer.go

**Comment by qcdll** [comment]
in a live network, just imposing some reasonable read timeout will force disconnect of dead peers

I don't really see what benefit ping/pong can bring us, or a mechanism to periodically ping

that said, it won't hurt to have those commands at our dispose, so we are just going to add that

**Comment by ninjaahhh** [comment]
why re-opened?

**Comment by qcdll** [comment]
need to add some handler for the commands
