### ISSUE TITLE
Bootstrap archive not updated by the team since 04-Apr-19

### ISSUE THREAD

**Issue by Bambarello** [QuarkChain/pyquarkchain#465]
Please advise why bootstrap archive not updated regularly, eg twice a day, as it was done before?
Now the file is 4-days old which is causing serious issues for re-sync and fresh node start.

curl https://s3-us-west-2.amazonaws.com/testnet2/data/25/$(curl -s https://s3-us-west-2.amazonaws.com/testnet2/data/25/LATEST).tar.gz

(LATEST is - 2019-04-04)

**Comment by ninjaahhh** [comment]
thanks for pointing out. seems we've had some access control hiccups. now it should be fixed.

will fully close the issue once we confirm the cronjob runs successfully.

**Comment by ninjaahhh** [comment]
confirmed the cronjob works as expected
