### ISSUE TITLE
Initial node sync status - incorrect via JSON RPC

### ISSUE THREAD

**Issue by Bambarello** [QuarkChain/pyquarkchain#466]
Please note, when node restarted, and looking for peers, uploaded only root block up to the latest stage -> it's reporting the sync status as "False", while it shall be "True" even if node is just initially looking for nodes around.

```
IP:                 localhost  
Chains:             6  
Network Id:         25  
Peers:                                                   
                                                          
Timestamp             Syncing    ROOT CHAIN/SHARD-HEIGHT 
2019-04-08 17:37:48     False   34613                   
2019-04-08 17:38:03     False   34613 
```

**Comment by qizhou** [comment]
syncing means a node finds a peer with a higher TD of root block and tries to download the blocks.  However, since it is still looking for nodes nearby and cannot confirm that who has a higher TD or not, the synchronization won't start at the moment.

**Comment by Bambarello** [comment]
Yes, I understand you logic, however the idea is to write the node watchdog, which is quarying JSON status of node, and if its behind and sync status is False -> restart the node.

The current approach to report sync "False" while node is looking for peers and root block is not really good, as it's misleading, the node is initial phase of Sync, so I suggest changing the JSON output to "True" anyway, and use sync status "False" only for fully synchronized node with connected peers.

What do you think?

**Comment by qizhou** [comment]
I think currently the column just reflects the state of our synchronizer, not the state of the node.  We may introduce another column that indicates the state of the node like # of peers connected, connecting.

**Comment by Bambarello** [comment]
That exactly what I mean. The state of synchronizer reported via JSON during intitial node connection stage shall not be "False", this is misleading. Change to True for initial stage as well, this will allow the external node watchdog script to analyze this stage correctly.

I mean this output:

{"jsonrpc": "2.0", "result": {"networkId": 25, "chainSize": 6, "shardServerCount": 4, "rootHeight": 37570, "rootDifficulty": 1002932549453, "rootCoinbaseAddress": "0xd50f23e410711c1391f5ef88fc11245e564c768400
000000", "rootTimestamp": 1554968399, "rootLastBlockTime": 78, "txCount60s": 1, "blockCount60s": 49, "staleBlockCount60s": 0, "pendingTxCount": 1, "totalTxCount": 3470, **"syncing": false,** "mining": false, "shards":

**Comment by qizhou** [comment]
Our hands are tight with mainnet launch.  Feel free to get your hands dirty :)

**Comment by Bambarello** [comment]
Ok, let it be as is in testnet.
