### ISSUE TITLE
Will you issue new docker release (2.5.5) based on latest Master commits?

### ISSUE THREAD

**Issue by Bambarello** [QuarkChain/pyquarkchain#467]
I see a lot of commits, but we can't update our docker nodes, which might be helpful for sync issues. Can you release update?

**Comment by qcdll** [comment]
one way is to login to the docker and run git pull

but recently the released docker image looks to be only on the release branch only, what you want to do is:
```
vi .git/config
```
change to `+refs/heads/*:refs/remotes/origin/*` and then run `git pull` it should pull the latest master

**Comment by qcdll** [comment]
also beware of the risk of running latest master, it may or may not be compatible with current running testnet

**Comment by Bambarello** [comment]
That is why we expect the dev team to produce new release instead of community pulling various versions from github (which may lead to even more mess).

**Comment by qcdll** [comment]
unless there are issues with current release we'd like to maintain a schedule. Is there anything in the current release that's causing issues? please let us know

**Comment by Bambarello** [comment]
It's sometimes difficult to identify the issue. For example one node, with properly forwarded ports experiences strange peering issues - able to connect to only 1-2-3 nodes and not increasing the peering.

Here is the warning log


```
MASTER: W0409 21:24:44.715403 nat.py:120] No NAT mapping has been set
MASTER: E0409 21:24:45.203553 peer.py:1056] Disconnected during handshake <Node(0x5eeaae0986bb6d7e36fd3a23ae15ca371ba9e88e8545825ed587a472b5ec417c3f757ee46e643d834a7ff454855cfc28b736b8b76f2eae3ebbe61028b777971c@35.155.213.180:38291)>: HandshakeDisconnectedFailure('QuarkPeer <Node(0x5eea@35.155.213.180)> disconnected before completing sub-proto handshake: too_many_peers',)
MASTER: E0409 21:24:45.204801 peer.py:1066] Closing connection to <Node(0x5eeaae0986bb6d7e36fd3a23ae15ca371ba9e88e8545825ed587a472b5ec417c3f757ee46e643d834a7ff454855cfc28b736b8b76f2eae3ebbe61028b777971c@35.155.213.180:38291)>
MASTER: E0409 21:25:02.544282 peer.py:1050] Could not complete handshake with <Node(0x8f6873d2f8e028a633a4a9ea900ea8d4dca5dd54a13dcf8dfde0834417fc295e04f24eaaf7ebc2cdb74f06d046c3121f0b44676b178b3c1e85416953dfc98edc@203.173.42.76:2139)>: UnreachablePeer()
MASTER: W0409 21:25:14.815045 kademlia.py:236] Cannot get 25 nodes as RoutingTable contains only 0 nodes
SLAVE_S1: W0409 21:26:14.520937 shard_state.py:516] Failed to add transaction: <Transaction(e3a0)>: 'nonce' actual:2488 target:2474
MASTER: W0409 21:28:57.429498 kademlia.py:236] Cannot get 25 nodes as RoutingTable contains only 2 nodes
MASTER: W0409 21:32:23.853228 kademlia.py:236] Cannot get 25 nodes as RoutingTable contains only 2 nodes
MASTER: W0409 21:35:44.125693 kademlia.py:236] Cannot get 25 nodes as RoutingTable contains only 2 nodes

```

**Comment by Bambarello** [comment]
By the way - the change above

`change to +refs/heads/*:refs/remotes/origin/* and then run git pull it should pull the latest master`

led do the error upon` git pull `command.  Can you please check if above is correctly referring to master version?

**Comment by ninjaahhh** [comment]
`git pull origin master` should force fetching and merging from the master

**Comment by qizhou** [comment]
Close the issue since it is stale.
