### ISSUE TITLE
难度调度可能被恶意调整

### ISSUE THREAD

**Issue by coakq** [QuarkChain/pyquarkchain#474]
难度调整主要取决于子父块时间差，对当前块的时间检验不严格可能存在时间伪造，通过调整时间增大计算难度，而整体难度检验是单调增大，可调整为依赖多个块调整一次难度

```python
def calculate_diff_with_parent(self, parent, create_time):
    check(parent.create_time < create_time)
    sign = max(1 - (create_time - parent.create_time) // self.cutoff, -99)
    offset = parent.difficulty // self.diff_factor
    return int(max(parent.difficulty + offset * sign, self.minimum_diff))

# ---

if self.tip.total_difficulty < block.header.total_difficulty:
    self.tip = block.header
    self.db.update_tip_hash(block_hash)
    self.__rewrite_block_index_to(block)
```

**Comment by qizhou** [comment]
该难度算法使用的是以太坊的难度算法，已经在以太坊网络上面验证。

**Comment by qcdll** [comment]
@coakq  how would you differentiate malicious timestamp manipulation and genuine clock skew? for example clock of a miner could be slower than others. And what kind of benefit can miners get from increasing difficulty on purpose? doesn't sound logical to me
