### ISSUE TITLE
Update dev doc

### ISSUE THREAD

**Issue by ninjaahhh** [QuarkChain/pyquarkchain#477]
https://developers.quarkchain.io/ is severely outdated.

should also include
1. code samples for deposit and withdrawal
1. reminder of different confirmation period from root chain and shard chain

please triage @qizhou

**Comment by qcdll** [comment]
there should be multinative token, what else is missing?

**Comment by ninjaahhh** [comment]
> there should be multinative token, what else is missing?

lots of parameter changes as well

**Comment by ninjaahhh** [comment]
after offline discussion, for now let's just put up a banner telling readers that the API is still unstable

**Comment by ninjaahhh** [comment]
close as a duplicate of #555
