### ISSUE TITLE
Verify token supply changes

### ISSUE THREAD

**Issue by ninjaahhh** [QuarkChain/pyquarkchain#479]
As outlined in [this post](https://medium.com/quarkchain-official/fixed-supply-token-model-with-dynamically-added-shards-chains-52db23a35aa3), the block reward should decrease accordingly. We need to verify such decrease in different stages and make sure the calculation is correct.

@qizhou up to you for triaging.

**Comment by qcdll** [comment]
the shard block coinbase in testnet 2.5 looks right, what else needs to be done?

**Comment by qizhou** [comment]
Here is the current configuration:

Rootchain:
      "EPOCH_INTERVAL": 10080
      "COINBASE_AMOUNT": 120000000000000000000,

Shard chain
        "EPOCH_INTERVAL": 60480
        "COINBASE_AMOUNT": 5000000000000000000,


Global
       "BLOCK_REWARD_DECAY_FACTOR": 0.88

For shard 0, block 60479, coinbase is 2.5 QKC
http://testnet2.quarkchain.io/block/0/0/60479
block 60480, coinbase is 2.2 QKC  = 2.5 * 0.88
http://testnet2.quarkchain.io/block/0/0/60480
block 120959, coinbase is 2.2 QKC
http://testnet2.quarkchain.io/block/0/0/120959
block 120960, coinbase is 1.936 QKC
http://testnet2.quarkchain.io/block/0/0/120960

For rootblock, block 10079, coinbase is 273.8 QKC = 54 * 2.2 + 14 * 2.5 + 120 (rootblock mining reward) QKC

block 10080, coinbase is 266.6 QKC = 55 * 2.2 + 16 * 2.5 + 105.6 (120 * 0.88) QKC

block 20159, coinbase is 250.096 QKC = 56 * 2.2 + 1.936 * 11 + 105.6 QKC

block 20160, coinbase is 160.072 QKC = 27 * 2.2 + 1.936 * 4 + 92.928 (120 * 0.88 * 0.88) QKC


looks like everything is working as intended lol.

**Comment by ninjaahhh** [comment]
yay
