### ISSUE TITLE
latest code cannot synchronize with testnet 2.5.4

### ISSUE THREAD

**Issue by qizhou** [QuarkChain/pyquarkchain#485]
This is expected behavior, but want to highlight the transaction that breaks the consensus:
- http://testnet2.quarkchain.io/tx/0xe32d22819936c5c486942ce1d2712b70545f50970bcbcb187a6820be954dbb7b00010001

where a transaction is failed due to PoSW constraint.  The transaction fee is 0.0003, however, shard block takes all fee, which is incorrect.  The fix 

https://github.com/QuarkChain/pyquarkchain/commit/c89084205605a9dd505008434b7098790a2a1733#diff-4ed4f9b5c7db61b0845e110616dae88c

changes the fee calculation so that half of the fee will be counted towards root block reward.

To make the synchronizer works in testnet 2.5.4, the above changes need to be reverted.

**Comment by qizhou** [comment]
Just FYI.

**Comment by ninjaahhh** [comment]
good to know
