### ISSUE TITLE
rocksdb may lose data after shutting down the machine/container directly

### ISSUE THREAD

**Issue by qizhou** [QuarkChain/pyquarkchain#486]
Default rocksdb options fsync is disabled, which means that the data are not written to disk (in os memory) after db put operation.  This is acceptable for performance optimization.  However, this also implies that if a master/slave's machine/container is shutdown, and the cluster crashes, restarting the cluster may lead to an inconsistent state, which should be detected and recovered.

>>> import rocksdb
>>> a = rocksdb.Options()
>>> a.use_fsync
False

**Comment by qizhou** [comment]
@ninjaahhh This may relate to the inconsistent state you found.

**Comment by ninjaahhh** [comment]
but from this [updated comment](https://github.com/bdarnell/rocksdb/commit/34971ed8ec16931c5661f447e6dc4dded7c6ae62), `use_fsync` doesn't seem like a fix?

note in our production env, kernel version is 4.4.0 and file system is ext4

**Comment by qizhou** [comment]
Interesting.  Oh, btw, a lot of system may not implement fsync and fdatasync well, especially in container env (I remember vmware vm may ignore fsync and fdatasync for performance reason).

**Comment by qizhou** [comment]
close it at the moment.  Will re-open it if we discover more clue from rocksdb
