### ISSUE TITLE
Not getting correct data output with stats tool

### ISSUE THREAD

**Issue by thezla** [QuarkChain/pyquarkchain#492]
I'm running the "stats" tool with python3 like so: `python3 stats --ip=localhost`.
I'm using a local network with 5 nodes, each on a different machine, where one of them has "--start_simulated_mining" toggled.
In the README it says I should get a table with a lot of data printed to the terminal, but I'm only getting the following:

> CPU:                4
> Memory:             0 GB
> IP:                 localhost
> Chains:             3
> Network Id:         3
> Peers:              192.168.0.13:38291, 192.168.0.10:38291, 192.168.0.8:38291, 192.168.0.9:38291
> 
> Timestamp             Syncing    ROOT CHAIN/SHARD-HEIGHT
> 2019-04-15 13:23:29     False       0 0/0-309 0/1-305 1/0-298 1/1-287 2/0-292 2/1-317
> 2019-04-15 13:23:39     False       0 0/0-314 0/1-305 1/0-301 1/1-289 2/0-292 2/1-321
> 2019-04-15 13:23:49     False       0 0/0-317 0/1-306 1/0-303 1/1-290 2/0-297 2/1-321
>.
>.
>.

Am I doing something wrong?

**Comment by qizhou** [comment]
I think this is the table of the data?  Are you expected any other data from README?

**Comment by thezla** [comment]
I was expecting it to look like this:

```
----------------------------------------------------------------------------------------------------
Timestamp                     TPS   Pending tx  Confirmed tx       BPS      SBPS      ROOT       CPU
----------------------------------------------------------------------------------------------------
2018-09-21 16:35:07          0.00            0             0      0.00      0.00        84     12.50
2018-09-21 16:35:17          0.00            0          9000      0.02      0.00        84      7.80
2018-09-21 16:35:27          0.00            0         18000      0.07      0.00        84      6.90
2018-09-21 16:35:37          0.00            0         18000      0.07      0.00        84      4.49
2018-09-21 16:35:47          0.00            0         18000      0.10      0.00        84      6.10
```

Is there any way to get TPS and pending tx?

**Comment by qizhou** [comment]
You may need to try verbose -v or --verbose.

**Comment by thezla** [comment]
Okay that worked, thanks.
I was wondering aswell what the "id" parameter when loadtesting means. Since I'm not seeing any generated transactions when sending the following command:
curl -X POST --data '{"jsonrpc":"2.0","method":"createTransactions","params":{"numTxPerShard":100, "xShardPercent":10},"id":3}' http://localhost:38491

**Comment by ninjaahhh** [comment]
@thezla you will need to start the simulated mining process by invoking `setMining` method

```
curl -X POST -H "Content-Type: application/json" localhost:38491 -d '{"jsonrpc": "2.0", "method": "setMining", "params": [true], "id": 42}'
```

**Comment by qizhou** [comment]
going to close the issue since the solution was given.  please open a new issue if you have any other questions.
