### ISSUE TITLE
bootnode still connecting peers even MAX_PEERS=0

### ISSUE THREAD

**Issue by qizhou** [QuarkChain/pyquarkchain#534]
Observe the following message in bootnode with MAX_PEERS=0, not sure it is expected or not.

MASTER: I0424 05:06:18.586930 peer.py:1127] Connected peers: 14 inbound, 11 outbound

**Comment by qizhou** [comment]
Should we close this because of recent commit?

**Comment by qcdll** [comment]
https://github.com/QuarkChain/pyquarkchain/commit/befd98e7e0babbcbf1667a9ccd7dc2827668a6f0
