### ISSUE TITLE
Illegal instruction (Core dumped), when running cluster.py on provided AWS Image

### ISSUE THREAD

**Issue by thezla** [QuarkChain/pyquarkchain#548]
When I run the following command:
`pypy3 cluster.py --p2p --privkey= <My Key>`
The program crashes and I get an error: `"Illegal Instruction (Core Dumped)"`.

I am using the provided AWS image from here:
https://github.com/QuarkChain/pyquarkchain/wiki/Setting-up-a-QKC-Miner-in-5-Minutes-with-AWS

Image name: ami-0bc201609b49cc40f

**Comment by ninjaahhh** [comment]
@jyouyj please take a look, my guess is that instruction could be out-dated

per the question itself, I would recommend following the [dockerfile](https://github.com/QuarkChain/pyquarkchain/blob/master/mainnet/singularity/Dockerfile) to install the dependency, or even better, use [the docker image directly](https://github.com/QuarkChain/pyquarkchain/releases/tag/mainnet1.0.1)

as for the config, it's recommended to use a config JSON file as the cmd argument. e.g. [this one](https://github.com/QuarkChain/pyquarkchain/blob/master/mainnet/singularity/cluster_config_template.json) is for mainnet

**Comment by thezla** [comment]
Is there a config file for starting a private cluster just for testing?

**Comment by thezla** [comment]
Also,
Also, I tried the docker image and started as was recommended with the required ports open.
When I tried to run cluster.py I got `libstdc++.so.6: version 'CXXABI_1.3.11' not found` and the program exited. I am running **Ubuntu 18.04** on an AWS. I was not using a config file at that time, is that the reason or is it something else? I will try with a config file as well as soon as I get the time.

**Comment by qizhou** [comment]
I would also suggest using python3 instead of pypy3 for better stability.

- Qi

**Comment by jyouyj** [comment]
I will provide a mainnet cluster AMI later today.

**Comment by jyouyj** [comment]
@thezla 
AWS Mainnet AMI name: QuarkChain_Mainnet_Cluster_AMI
AMI ID: ami-0750b30fd2b17b65c
Region: Oregon 
Please follow the instructions
https://github.com/QuarkChain/pyquarkchain/wiki/Run-a-Private-Cluster-on-the-QuarkChain-Testnet-2.0

**Comment by thezla** [comment]
I tried the new AWS image and I cannot run cluster.py with pypy3 or with python3.
Seems like there are modules missing. Do I need to enter the virtualenv beforehand? If so, in what directory can I find it?

Python3:
```
ubuntu@ip:~/pyquarkchain/quarkchain/cluster$ python3 cluster.py --p2p --privkey=...
Traceback (most recent call last):
  File "cluster.py", line 10, in <module>
    from quarkchain.cluster.cluster_config import ClusterConfig
ModuleNotFoundError: No module named 'quarkchain'
```

pypy3:
```
ubuntu@ip:~/pyquarkchain/quarkchain/cluster$ pypy3 cluster.py --p2p --privkey=...
Traceback (most recent call last):
  File "cluster.py", line 10, in <module>
    from quarkchain.cluster.cluster_config import ClusterConfig
  File "/home/ubuntu/pyquarkchain/quarkchain/cluster/cluster_config.py", line 11, in <module>
    from quarkchain.config import BaseConfig, ChainConfig, QuarkChainConfig
  File "/home/ubuntu/pyquarkchain/quarkchain/config.py", line 10, in <module>
    import quarkchain.db
  File "/home/ubuntu/pyquarkchain/quarkchain/db.py", line 6, in <module>
    import rocksdb
ImportError: No module named 'rocksdb'
```

**Comment by thezla** [comment]
Thanks, I got it running now, I also hooked up the stats tool to the cluster.
Now I want to loadtest the network, I'm trying this command:
`curl -X POST --data '{"jsonrpc":"2.0","method":"createTransactions","params":{"numTxPerShard":10000, "xShardPercent":10},"id":0}' http://localhost:38491`
but nothing is happening.
I get this as output: `{"jsonrpc": "2.0", "result": null, "id": 0}`
I'm not seeing any transactions in the stats tool either.

**Comment by thezla** [comment]
I have also connected to the testnet and was wondering:
- Is there is a way to download all the blocks in one go without validating? I see there is a download link for the mainnet chain but is there one for the testnet?
- Will I be able to loadtest when on the testnet?
