### ISSUE TITLE
multiple entries of 115.212.51.28 in peers list

### ISSUE THREAD

**Issue by AGx10k** [QuarkChain/pyquarkchain#549]
peer 115.212.51.28 somehow appears multiple times in peerlist. seen it on all my clusters. for example once it was 14 of 21 of my peers (as seen in quarkchain/tools/stats)

not sure if it's a bug of p2p layer or a malicious node. 

it's also seen in explorer:
![strange-peerlist](https://user-images.githubusercontent.com/48479505/57162086-7d65a180-6ded-11e9-8714-a0fcff72c7fc.JPG)

found by @Bambarello

**Comment by qizhou** [comment]
Nice catch!  @qcdll could you please take a look?

**Comment by qcdll** [comment]
yeah it looks there are multiple 115.212.51.28 in the routing table w/different identity. I suggest turning NO_SAME_IP to True, I am also making a commit to fix it
