### ISSUE TITLE
SLAVE_S3 dying out of nowhere

### ISSUE THREAD

**Issue by entinio** [QuarkChain/pyquarkchain#550]
mainnet, docker image

```
SLAVE_S3 is dead. Shutting down the cluster...
================================ SHUTTING DOWN CLUSTER ================================
SIGTERM >>> -u master.py --cluster_config=/code/pyquarkchain/mainnet/singularity/cluster_config_template.json
SIGTERM >>> -u slave.py --cluster_config=/code/pyquarkchain/mainnet/singularity/cluster_config_template.json --node_id=S0
SIGTERM >>> -u slave.py --cluster_config=/code/pyquarkchain/mainnet/singularity/cluster_config_template.json --node_id=S1
SIGTERM >>> -u slave.py --cluster_config=/code/pyquarkchain/mainnet/singularity/cluster_config_template.json --node_id=S2
```

**Comment by ninjaahhh** [comment]
restart should help :)

crash could happen for many reasons, it would be great if you can provide more details, especially logs from that crashed slave

**Comment by entinio** [comment]
Do you realise I can't restart automatically because the mining power will create a fork ? I have to stop all the rigs manually and then restart... which is a pain !

**Comment by entinio** [comment]
You will have to tell me where this log is, because I don't see any log file within the docker bash architecture. Not even in /var/log

**Comment by entinio** [comment]
This is the only information I get

```
(...)
MASTER: I0508 01:06:05.456150 jsonrpc.py:462] {"id":3,"jsonrpc":"2.0","method":"getWork","params":["0x30001"]}
SLAVE_S2 is dead. Shutting down the cluster...
================================ SHUTTING DOWN CLUSTER ================================
SIGTERM >>> -u master.py --cluster_config=/code/pyquarkchain/mainnet/singularity/cluster_config_template.json
SIGTERM >>> -u slave.py --cluster_config=/code/pyquarkchain/mainnet/singularity/cluster_config_template.json --node_id=S0
SIGTERM >>> -u slave.py --cluster_config=/code/pyquarkchain/mainnet/singularity/cluster_config_template.json --node_id=S1
SIGTERM >>> -u slave.py --cluster_config=/code/pyquarkchain/mainnet/singularity/cluster_config_template.json --node_id=S3
```

I got 4 rigs asking works from this node. i5 and 8go isn't enough ?

Btw, isn't it possible to restart it automatically without the existing mining power creating a fork ?

**Comment by qizhou** [comment]
It should have more logs before.  In general, i5 with 8g should be enough
for running weeks.

You could create a script that tries to restart your cluster if it exists.

- Qi

**Comment by ninjaahhh** [comment]
have seen similar cases, and potentially is oom. 16g mem is recommended. close for inactivity.
