### ISSUE TITLE
Investigate indexing node shutdown

### ISSUE THREAD

**Issue by ninjaahhh** [QuarkChain/pyquarkchain#562]
error log:

https://gist.github.com/ninjaahhh/9c6b22761e081f4cc0b09704dff4c2d7

seems like to be inconsistent state between root chain and shard chain again. this particular instance is solved by reverting to a previous snapshot and restart syncing. 

cc @qizhou

**Comment by qizhou** [comment]
Interesting.  Do you have the db files of the cluster so that I could browse and check?

**Comment by ninjaahhh** [comment]
> Interesting. Do you have the db files of the cluster so that I could browse and check?

ah I deleted the snapshot. will try to record one next time

**Comment by ninjaahhh** [comment]
we suspect it's again caused by snapshot server stopping/starting docker (same as #486) which caused unexpected inconsistencies. I updated snapshot server to use `supervisor`, hopefully the issue will be solved.

close for now until we see another instance and retain the db snapshot.
