### ISSUE TITLE
team testing addresses not excluded from testnet mining results

### ISSUE THREAD

**Issue by AGx10k** [QuarkChain/pyquarkchain#576]
during testnet in discord it was mentioned by junjiah ([screenshot](https://prnt.sc/o2dfwc)) that there are some addresses of developers which will be excluded from mining results. they were not excluded.
this one if from [Testnet Mining Result
](https://github.com/QuarkChain/pyquarkchain/wiki/Testnet-Mining-Result)
`d50f23e410711c1391f5ef88fc11245e564c7684, 27120.775`

i suggest subtracting this and other testing addresses and redistribute proceeds evenly across affected shards/chains miners

**Comment by ninjaahhh** [comment]
thanks for reminding, we will take a closer look at all mining addresses from the team and redistribute those reward tokens

**Comment by jyouyj** [comment]
Thanks for reminding. The address "d50f23e410711c1391f5ef88fc11245e564c7684b9ab75b2" and "fee3d08216f0bfe96a5c0f5df9ec9b2577ad64f0" are our team's mining addresses. We will burn the tokens in these addresses after enabling the transactions (the end of June).

**Comment by AGx10k** [comment]
burn is OK in my opinion. thanks!

**Comment by ninjaahhh** [comment]
re-open for tracking purposes. will confirmed burning once tx is enabled.

**Comment by ninjaahhh** [comment]
@jyouyj let's burn those tokens since transactions are enabled now

**Comment by jyouyj** [comment]
The testnet mining rewards in these two addresses have been burned. The corresponding transaction id are 0xa0d44f23250e321c8dae18b7df34a365b8c0b01b7f4c1563d82a106f790f41210000ef5e and 0x057958628c089fa28c068c81eefc3f7a9dedadff141256e8c5f18dfbf82d930800000f25.
@ninjaahhh @ninjaahhh @

**Comment by jyouyj** [comment]
The testnet mining rewards in these two addresses have been burned. The corresponding transaction id are 0xa0d44f23250e321c8dae18b7df34a365b8c0b01b7f4c1563d82a106f790f41210000ef5e and 0x057958628c089fa28c068c81eefc3f7a9dedadff141256e8c5f18dfbf82d930800000f25 @AGx10k

**Comment by qizhou** [comment]
We should publish an announcement in at least mining group.

- Qi
