### ISSUE TITLE
broadcast blocks before add_block

### ISSUE THREAD

**Issue by qcdll** [QuarkChain/pyquarkchain#63]
current measurements on loadtest shows 10x+ propagation latency when loadtesting, we now try broadcasting blocks right after POW validation, instead of waiting for local add_block

for slave:
1. move broadcast before add_block
2. allow peers to download blocks that are in a pool, instead of just from the chain

**Comment by ninjaahhh** [comment]
should we close this? @qcdll

**Comment by qcdll** [comment]
need to collect data for root block and do the same thing there if needed
