### ISSUE TITLE
POW/late

### ISSUE THREAD

**Issue by frode88** [QuarkChain/pyquarkchain#639]
Hi.
Why dos Qkc has no seed hash check mechanism - Cluster accepts the share even when already too late because of a new block. The cluster should not accept shares that for previse block .

**Comment by jyouyj** [comment]
Could you clarify your problem a little bit? Qkc uses the same hash mechanism as Ethereum.  One epoch is 30000 blocks.  Seed hash is uniquely determined by the height (epoch) of the block. Thus, it can be easily calculated from the epoch.

**Comment by frode88** [comment]
Hi. So what happed that Cluster accept the share/pow but no reward. Its Valid POW/Share and the cluster accept it. So every 10-12 vaild pow I get only 1 reward. I was thinking its Stale Shares but almost 9 of 10 valid pow without reward. Running Stratum.
