### ISSUE TITLE
Vaild pow no reward

### ISSUE THREAD

**Issue by frode88** [QuarkChain/pyquarkchain#651]
Hi.
I have been testing the cluster. So I used Nanominer and Ethminer(QKC) every time miner send vaild pow to the cluster, so cluster accepted it but no reward. The last test was ten valid pows; only 7 got the reward. Is it something wrong with the cluster? Even build docker image from GitHub and tested- the same results

**Comment by frode88** [comment]
![1](https://user-images.githubusercontent.com/22121200/61579831-aa7f4180-ab0a-11e9-9f04-7bd4afcab7d5.PNG)
![2](https://user-images.githubusercontent.com/22121200/61579832-aa7f4180-ab0a-11e9-9f4b-28107a851d57.PNG)

**Comment by frode88** [comment]
MASTER: I0720 19:24:41.709125 jsonrpc.py:471] {"jsonrpc": "2.0", "method": "submitWork", "params": ["0x70001", "0x7a5b9540d9474df5a255d54ff22e5e3c7ad79309e4b38c9754f98d79a781d11c", "0xa35788afd2488ba2", "0x1a76624daf66ccca3b969df0a0f033455a93cf80e6d68ed90f8561e45a36e8ae"], "id": 20}

any one can tell when what the use of this ID thing?  "id": 20}

**Comment by ninjaahhh** [comment]
my guess would be some other miners may have posted a valid block at the same height, and they became the longest chain.

maybe the calculation of total shares inside Ethminer(QKC) is incorrect?  @jyouyj can chime in

**Comment by frode88** [comment]
> my guess would be some other miners may have posted a valid block at the same height, and they became the longest chain.
> 
> maybe the calculation of total shares inside Ethminer(QKC) is incorrect? @jyouyj can chime in

Hi.
This is picture of Nanominer. but Etherminer are the same.

**Comment by sheprnd** [comment]
> my guess would be some other miners may have posted a valid block at the same height, and they became the longest chain.
> 
> maybe the calculation of total shares inside Ethminer(QKC) is incorrect? @jyouyj can chime in
Looks like it works so because of long confirmation term from node.
I made a ping to boot nodes and leave only one of them, with smallest ping time. It decreased loss in 2 times from 30% to 10-15%.
