### ISSUE TITLE
Run check_db every day

### ISSUE THREAD

**Issue by qizhou** [QuarkChain/pyquarkchain#658]
Need to run check_db every day against the latest code to make sure we don't break existing consensus.

**Comment by qizhou** [comment]
Will it send a warning email in case the test failed?  Looks like cluster.py doesn't return exit code of master/slave processes

**Comment by ninjaahhh** [comment]
it does 

https://github.com/QuarkChain/pyquarkchain/blob/ba8992b6e40779b54232b377eed6488bb9ce1e13/quarkchain/cluster/cluster.py#L111-L128
