### ISSUE TITLE
Display posw info in stats page

### ISSUE THREAD

**Issue by qizhou** [QuarkChain/pyquarkchain#673]

**Comment by qizhou** [comment]
We also need per-block posw information, such as effective difficulty, and allowance.

**Comment by ninjaahhh** [comment]
besides per-block info, what kind of information is needed in stats page?

**Comment by qizhou** [comment]
Difficulty After PoS, PoSW parameters, and a link to calculator

**Comment by ninjaahhh** [comment]
I'm thinking about showing a info box when hovering (or tapping, on a mobile phone) on the difficulty in each shard, which includes following stats:

1. average effective difficulty for last 256 blocks
2. posw used / posw allowed ratio
3. posw parameters 

what do you think? @qizhou

**Comment by qizhou** [comment]
I think we could create a calculator panel with the following information:
- Chain/Shard
- Height
- Difficulty
- Difficulty with Stake
- Minimum Stake (1/256)
- Maximum Stake (256/256)
- Expected Return vs ETH with Stake

**Comment by ninjaahhh** [comment]
> I think we could create a calculator panel with the following information:
> 
> * Chain/Shard
> * Height
> * Difficulty
> * Difficulty with Stake
> * Minimum Stake (1/256)
> * Maximum Stake (256/256)
> * Expected Return vs ETH with Stake

detailed cost/profit information will be shown in a separate calculator page. for the stats page we will show basic posw configs like window size, minimum staking, effective difficulty, etc.
