### ISSUE TITLE
evm call check

### ISSUE THREAD

**Issue by 516108736** [QuarkChain/pyquarkchain#708]
https://github.com/QuarkChain/pyquarkchain/blob/b7d08c78ab2c29e43c4b38a7ebea3b42d61bb5cd/quarkchain/evm/vm.py#L814

need add  token_id_queried=msg.token_id_queried？
check it ?

**Comment by ninjaahhh** [comment]
I think it's been added here

https://github.com/QuarkChain/pyquarkchain/blob/b7d08c78ab2c29e43c4b38a7ebea3b42d61bb5cd/quarkchain/evm/vm.py#L848-L850
