### ISSUE TITLE
some opcode not working properly for multinative token

### ISSUE THREAD

**Issue by ninjaahhh** [QuarkChain/pyquarkchain#746]
namely, `BALANCE` and `SELFDESTRUCT`

**Comment by ninjaahhh** [comment]
also the way we handle `payable` for non-default token

**Comment by qizhou** [comment]
What is the plan to fix the problem?  I think balance should be fixed and selfdestruct may just return the default value or token to be refund.

**Comment by ninjaahhh** [comment]
since we don't want to break existing `BALANCE` opcode, one solution would be to add a `BALANCES` opcode which uses one stack parameter as token ID.

for `SELFDESTRUCT` we don't need to introduce new opcodes, but need to update the behavior: instead of only sending one token balance to the specified address, should send ALL token balances

**Comment by ninjaahhh** [comment]
since for now we don't have any non-default tokens, the priority is relative low

**Comment by ninjaahhh** [comment]
bump up the priority since we will enable this feature very soon. easiest solution will be using another pre-compiled contract for querying native token's balance

**Comment by ninjaahhh** [comment]
> for `SELFDESTRUCT` we don't need to introduce new opcodes, but need to update the behavior: instead of only sending one token balance to the specified address, should send ALL token balances

hmm realized it doesn't make much sense to send ALL tokens when selfdestucting a contract, which may expose more attacking vectors (DDoS maybe) when having too many native tokens. will keep current behavior unchanged: only default tokens will be sent (however this means the total supply of non-default tokens may not add up)
