### ISSUE TITLE
Bug Transaction

### ISSUE THREAD

**Issue by silentnight187** [QuarkChain/pyquarkchain#768]
Hello sir 
Please help me 
my transaction still pending 8 Hours in QKC Blockchain 
![IMG_20191009_192303_270](https://user-images.githubusercontent.com/41644207/66481473-35992380-eacb-11e9-9edc-3ff698616dee.jpg)

**Comment by ninjaahhh** [comment]
it should only be a display issue, the transaction is either false (say, with a conflicting nonce), or should happen in the future.

the display problem is already addressed in https://github.com/QuarkChain/pyquarkchain/pull/749 and https://github.com/QuarkChain/pyquarkchain/issues/762
