### ISSUE TITLE
snapshot update time should be every 24 hours  in wiki ,but it shows every 12 hours 

### ISSUE THREAD

**Issue by tomdong2010** [QuarkChain/pyquarkchain#786]
![image](https://user-images.githubusercontent.com/19581409/68751736-1303a880-063d-11ea-8eac-6568788fb34f.png)

https://github.com/QuarkChain/pyquarkchain/wiki/Start-Clusters-on-the-QuarkChain

**Comment by ninjaahhh** [comment]
thanks for pointing out. updated.
