### ISSUE TITLE
Failure handling when using native token to pay for gas

### ISSUE THREAD

**Issue by ninjaahhh** [QuarkChain/pyquarkchain#797]
**background**:

when running a tx, if we find the gas token is different with default token (QKC), we will call the system contract's `payAsGas` function to update the contract storage and get back corresponding converted gas price in QKC, then deduct the system contract's QKC balance.

**problem**:

as asked in this PR https://github.com/QuarkChain/pyquarkchain/pull/794#discussion_r349363463, if the contract call failed or the system contract doesn't have enough QKC, how should we handle the transaction? note that:

1. it's not enough to pre-run the contract call during validation when adding the tx (i.e. before it's added to the block) to get the execution result and reject if failed: because the actual environment may be different when running the block v.s. validating the transaction
2. one goal of using native token to pay gas is to unify miners' reward tokens as QKC. so I think it's undesirable to simply mark the transaction failed and give the used gas to miner as a non-QKC token

**potential solutions**:

1. discard the block if such situation happens, i.e. force the node to make sure state is valid (e.g. system contract has enough QKC, contract call has to succeed) when adding transaction. however this needs us to update how we keep track of state when accepting transactions
1. fail the transaction, but no rewards to miner, burn part of the gas as dictated by `refund_rate` (however the miner will be less incentivized to accept these kind of transactions)

cc @qizhou

**Comment by qizhou** [comment]
Here are some of my thoughts:

If a system contract doesn't have sufficient QKC, I think such tx will be invalid and should never be included in a block (e.g., create a block to mine will discard such tx).  This is essentially to disallow the native token to be used as a gas token and someone needs to refill QKC to system contract.

If the contract call fails, then we will return the rest un-used gas as QKC (after refund discount).

**Comment by ninjaahhh** [comment]
agree on first part: if system contract doesn't have enough balance, throw it away as invalid tx.

on the second part if contract call `payAsGas` failed, I would suggest also treating it as invalid tx (as currently implemented in #796 [[line](https://github.com/QuarkChain/pyquarkchain/pull/796/files#diff-4ed4f9b5c7db61b0845e110616dae88cR168)]). because if that call failed, we don't know the equivalent amount of gas in QKC

**Comment by qizhou** [comment]
Yes, I agree that if the system contract call fails, we will treat the tx as an invalid one.

**Comment by ninjaahhh** [comment]
closed by #796
