### ISSUE TITLE
Root block conversion to proto 

### ISSUE THREAD

**Issue by lyhe18** [QuarkChain/pyquarkchain#828]
The libra shards only need a simplified structure of root block to do later work, thus we construct a simplified libra root block to be broadcast by root chain. In this issue, we will define the simplified libra root block structure in grpc_client.proto and finish the function of setting confirmed root blocks in grpc_client.py. Related to #830

**Comment by ninjaahhh** [comment]
can close? please link to the corresponding PR @lyhe18

**Comment by lyhe18** [comment]
Linked to pr 830.
