### ISSUE TITLE
[e2e] Skip check linked header

### ISSUE THREAD

**Issue by FreshmanQ** [QuarkChain/pyquarkchain#860]
same reason as #858, this check is unuseful, since we don't have to check if the new root block is sent back to the right shard chain in `root_state.validate_block`.

**Comment by ninjaahhh** [comment]
do you mean `RootState.is_same_chain` function? it's not checking if in same shard, but whether 2 headers are correctly linked. but you are right, we don't need to do the validation.

please update the title of the issue
