### ISSUE TITLE
Python -m pytest got ImportError: cannot import name 'cluster_pb2' error

### ISSUE THREAD

**Issue by chenyanghong** [QuarkChain/pyquarkchain#865]
=========================================== test session starts ===========================================
platform linux -- Python 3.6.9[pypy-7.3.0-final], pytest-3.6.4, py-1.8.1, pluggy-0.7.1
rootdir: /data/appuser/pyquarkchain, inifile:
plugins: timeout-1.3.3, asyncio-0.9.0
collected 176 items / 10 errors                                                                           

================================================= ERRORS ==================================================
________________________ ERROR collecting quarkchain/cluster/tests/test_cluster.py ________________________
ImportError while importing test module '/data/appuser/pyquarkchain/quarkchain/cluster/tests/test_cluster.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
quarkchain/cluster/tests/test_cluster.py:14: in <module>
    from quarkchain.cluster.tests.test_utils import (
quarkchain/cluster/tests/test_utils.py:10: in <module>
    from quarkchain.cluster.master import MasterServer, ClusterMaster
quarkchain/cluster/master.py:15: in <module>
    from quarkchain.generated import cluster_pb2, cluster_pb2_grpc
E   ImportError: cannot import name 'cluster_pb2'
________________________ ERROR collecting quarkchain/cluster/tests/test_filter.py _________________________
ImportError while importing test module '/data/appuser/pyquarkchain/quarkchain/cluster/tests/test_filter.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
quarkchain/cluster/tests/test_filter.py:5: in <module>
    from quarkchain.cluster.tests.test_shard_state import create_default_shard_state
quarkchain/cluster/tests/test_shard_state.py:8: in <module>
    from quarkchain.cluster.tests.test_utils import (
quarkchain/cluster/tests/test_utils.py:10: in <module>
    from quarkchain.cluster.master import MasterServer, ClusterMaster
quarkchain/cluster/master.py:15: in <module>
    from quarkchain.generated import cluster_pb2, cluster_pb2_grpc
E   ImportError: cannot import name 'cluster_pb2'
______________________ ERROR collecting quarkchain/cluster/tests/test_grpc_client.py ______________________
ImportError while importing test module '/data/appuser/pyquarkchain/quarkchain/cluster/tests/test_grpc_client.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
quarkchain/cluster/tests/test_grpc_client.py:8: in <module>
    from quarkchain.generated import cluster_pb2
E   ImportError: cannot import name 'cluster_pb2'
______________________ ERROR collecting quarkchain/cluster/tests/test_grpc_server.py ______________________
ImportError while importing test module '/data/appuser/pyquarkchain/quarkchain/cluster/tests/test_grpc_server.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
quarkchain/cluster/tests/test_grpc_server.py:6: in <module>
    from quarkchain.cluster.tests.test_utils import get_test_env
quarkchain/cluster/tests/test_utils.py:10: in <module>
    from quarkchain.cluster.master import MasterServer, ClusterMaster
quarkchain/cluster/master.py:15: in <module>
    from quarkchain.generated import cluster_pb2, cluster_pb2_grpc
E   ImportError: cannot import name 'cluster_pb2'
________________________ ERROR collecting quarkchain/cluster/tests/test_jsonrpc.py ________________________
ImportError while importing test module '/data/appuser/pyquarkchain/quarkchain/cluster/tests/test_jsonrpc.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
quarkchain/cluster/tests/test_jsonrpc.py:13: in <module>
    from quarkchain.cluster.jsonrpc import (
quarkchain/cluster/jsonrpc.py:16: in <module>
    from quarkchain.cluster.master import MasterServer
quarkchain/cluster/master.py:15: in <module>
    from quarkchain.generated import cluster_pb2, cluster_pb2_grpc
E   ImportError: cannot import name 'cluster_pb2'
_____________________ ERROR collecting quarkchain/cluster/tests/test_native_token.py ______________________
ImportError while importing test module '/data/appuser/pyquarkchain/quarkchain/cluster/tests/test_native_token.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
quarkchain/cluster/tests/test_native_token.py:4: in <module>
    from quarkchain.cluster.tests.test_utils import (
quarkchain/cluster/tests/test_utils.py:10: in <module>
    from quarkchain.cluster.master import MasterServer, ClusterMaster
quarkchain/cluster/master.py:15: in <module>
    from quarkchain.generated import cluster_pb2, cluster_pb2_grpc
E   ImportError: cannot import name 'cluster_pb2'
______________________ ERROR collecting quarkchain/cluster/tests/test_root_state.py _______________________
ImportError while importing test module '/data/appuser/pyquarkchain/quarkchain/cluster/tests/test_root_state.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
quarkchain/cluster/tests/test_root_state.py:6: in <module>
    from quarkchain.cluster.tests.test_utils import get_test_env
quarkchain/cluster/tests/test_utils.py:10: in <module>
    from quarkchain.cluster.master import MasterServer, ClusterMaster
quarkchain/cluster/master.py:15: in <module>
    from quarkchain.generated import cluster_pb2, cluster_pb2_grpc
E   ImportError: cannot import name 'cluster_pb2'
___________________ ERROR collecting quarkchain/cluster/tests/test_shard_db_operator.py ___________________
ImportError while importing test module '/data/appuser/pyquarkchain/quarkchain/cluster/tests/test_shard_db_operator.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
quarkchain/cluster/tests/test_shard_db_operator.py:5: in <module>
    from quarkchain.cluster.tests.test_utils import (
quarkchain/cluster/tests/test_utils.py:10: in <module>
    from quarkchain.cluster.master import MasterServer, ClusterMaster
quarkchain/cluster/master.py:15: in <module>
    from quarkchain.generated import cluster_pb2, cluster_pb2_grpc
E   ImportError: cannot import name 'cluster_pb2'
______________________ ERROR collecting quarkchain/cluster/tests/test_shard_state.py ______________________
ImportError while importing test module '/data/appuser/pyquarkchain/quarkchain/cluster/tests/test_shard_state.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
quarkchain/cluster/tests/test_shard_state.py:8: in <module>
    from quarkchain.cluster.tests.test_utils import (
quarkchain/cluster/tests/test_utils.py:10: in <module>
    from quarkchain.cluster.master import MasterServer, ClusterMaster
quarkchain/cluster/master.py:15: in <module>
    from quarkchain.generated import cluster_pb2, cluster_pb2_grpc
E   ImportError: cannot import name 'cluster_pb2'
_________________________ ERROR collecting quarkchain/cluster/tests/test_utils.py _________________________
ImportError while importing test module '/data/appuser/pyquarkchain/quarkchain/cluster/tests/test_utils.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
quarkchain/cluster/tests/test_utils.py:10: in <module>
    from quarkchain.cluster.master import MasterServer, ClusterMaster
quarkchain/cluster/master.py:15: in <module>
    from quarkchain.generated import cluster_pb2, cluster_pb2_grpc
E   ImportError: cannot import name 'cluster_pb2'
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 10 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
======================================== 10 error in 7.85 seconds =========================================
(virtu

**Comment by ninjaahhh** [comment]
the default `dev` branch is not for directly running. consider using `master` branch, or tag `mainnet-1.3.0`

**Comment by chenyanghong** [comment]
Thank you! The master branch can run normally.
How much disk space does the block currently have?

**Comment by ninjaahhh** [comment]
> Thank you! The master branch can run normally.
> How much disk space does the block currently have?

do you mean the whole blockchain size? from our snapshot it's ~65G

**Comment by chenyanghong** [comment]
thank you!   How do I set up blockchain snapshot synchronization? Since last night until now, only 7.4G data is synchronized. Is there any way to speed up the synchronization?

**Comment by ninjaahhh** [comment]
please refer to this detailed instruction https://github.com/QuarkChain/pyquarkchain/wiki/Start-Clusters-on-the-QuarkChain#quick-start---use-docker-image-to-start-a-cluster-and-mining

**Comment by chenyanghong** [comment]
thank you!  We need to develop a DAPP. We have n’t found the json api to create a wallet address, nor did we understand the json api for transfer. Is there a complete example?

**Comment by ninjaahhh** [comment]
low level jsonrpc doc: https://developers.quarkchain.io/#introduction
outdated but should-be-working js client: https://github.com/QuarkChain/quarkchain-web3.js/

if you have experiences developing ethereum-based dapps, those 2 things should be enough for you to get hands-on

**Comment by ninjaahhh** [comment]
close this issue now as it's not relevant anymore
