### ISSUE TITLE
duplicated processes found after running a cluster

### ISSUE THREAD

**Issue by qizhou** [QuarkChain/pyquarkchain#876]
Found duplicated processes after running run_cluster.sh
![image](https://user-images.githubusercontent.com/2541286/78612674-c2c0f900-781e-11ea-9009-5d01589bb88e.png)

Here is the snapshot of mainnet1.3
![image](https://user-images.githubusercontent.com/2541286/78612713-e126f480-781e-11ea-81fe-e0905a79bf12.png)

**Comment by ninjaahhh** [comment]
because for testnet we have separate simulated mining processes for root chain and shard chains. if you run against a mainnet config it should be fine

**Comment by qizhou** [comment]
Yes, just figure it out.  Thanks for the explanation.
