### ISSUE TITLE
Completed tx is not displayed in Metemask

### ISSUE THREAD

**Issue by qizhou** [QuarkChain/pyquarkchain#928]
Using devnet with EIP155

Send any QKC to another account.  Even the tx is completed, the tx in metamask activity page is still waiting:

![image](https://user-images.githubusercontent.com/2541286/131019542-297b9354-ef08-4193-b45a-96b2e9b10c73.png)

**Comment by ping-ke** [comment]
Metamask has been updated for Eip1559, it requires a new function GetBlockByHash, which is missing from our API. Now the feature has been added and deployed to devnet.

**Comment by qizhou** [comment]
Just checked on devnet, and now the issue seems to be fixed.
